- graphql-schemas/schema.yml
- schemas/aws/account-1.yml
part of https://issues.redhat.com/browse/APPSRE-4008
we need to support `aws` + `aws-us-gov` in our terraform integrations.
> add optional partition field to aws account schema

- graphql-schemas/schema.yml
- schemas/openshift/terraform-resource-1.yml
this PR changes the `assume_role` field of an AWS IAM role resource from string to an array of strings.
this is to allow defining a role with multiple IAM users that can assume it.
the `aws-iam-role` provider is currently not in use in the main app-interface repo, but only in use in the FedRamp environment.
the usage:
we mimic the AWS infrastructure access feature of OSD by creating an IAM role with the same [permissions](https://github.com/openshift/aws-account-operator/blob/84b11ddceb6baa5a2ee4fae56ce6fe686b415db8/hack/olm-registry/olm-artifacts-template.yaml#L105-L269) and permit usage of it to multiple users:
- the app-interface terraform user
- the hive iam user used to manage various VPC related resources in the cluster's aws account as part of the PrivateLink functionality: …
> terraform resource aws-iam-role assume_role to array

- graphql-schemas/schema.yml
query for users and get their gabi instances
> add backref from user to gabi instance

- graphql-schemas/schema.yml
- schemas/access/permission-1.yml
To be able to skip placeholder. Specifically for slakc-usergroup integration in this case, therefore updating the PermissionSlackUsergroup_v1 schema.
> Add skip property to permission schema to be able to skip placeholder.

- graphql-schemas/schema.yml
- schemas/openshift/terraform-resource-1.yml
part of https://issues.redhat.com/browse/APPSRE-4107
This allows for setting an OpenShift Service name as the target for an ALB
> terraform/alb: add support for targetting an openshift_service

- graphql-schemas/schema.yml
- schemas/app-sre/app-1.yml
- schemas/dependencies/status-page-1.yml
- schemas/dependencies/status-page-component-1.yml
Implementation based on the design doc coverd in APPSRE-3908
* dependencies/status-page-1.yml includes all required information to connect to a status page instance
* dependencies/status-page-component-1.yml represents a component on a status page
* app-sre/app-1.yml references status page components for documentation purposes
Ref APPSRE-3902
> Introduce schemas for status pages and their components

- schemas/app-sre/saas-file-2.yml
This was just a way to do a progressive rollout of the deployResources
option. Since all tekton resources are now controlled by the
openshift-tekton-resources integration, this is no longer needed
[APPSRE-3389](https://issues.redhat.com/browse/APPSRE-3389)
> Remove configurable resources option

- schemas/openshift/namespace-1.yml
There's a dedicated integration for this, so we shouldn't need to use
openshift-resources to manage tekton objects.
In case we have to, we could just revert this and make sure that both
integrations do not crash by using managed resource names in the
namespace file
APPSRE-3389
> Remove Tekton objects from openshift resources

- graphql-schemas/schema.yml
- schemas/dependencies/dns-zone-1.yml
part of https://issues.redhat.com/browse/APPSRE-4179
this will allow to reference a VPC from a DNS zone, making it "private".
> add vpc reference from dns-zone

- graphql-schemas/schema.yml
- schemas/aws/s3-1.yml
- schemas/openshift/terraform-resource-1.yml
It is requested in [APPSRE-3780](https://issues.redhat.com/browse/APPSRE-3780) by to add support for s3://insights-warehouse-prod and s3://insights-ingress-prod buckets to able to publish to a couple of SNS topics via arn.
This schema update will allow adding event notification as an array that configure SNS or SQS event notification to the bucket.
> Add Add support for SNS event notification for S3 and consolidate it with SQS

- graphql-schemas/schema.yml
- schemas/aws/s3-1.yml
- schemas/openshift/terraform-resource-1.yml
This was not consistent with the [terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification)
> Correct redundant plural.

- graphql-schemas/schema.yml
- schemas/openshift/terraform-resource-1.yml
ref: https://github.com/app-sre/qontract-reconcile/pull/2057
JIRA: APPSRE-3695
This schema change adds per-path targets instead of read/write targets. A sample config looks something like this:
```
provider: alb
...
targets:
- name: py2
openshift_service: py2-svc
default: true
- name: py3
openshift_service: py3-svc
rules:
- condition:
path: /v2/auth*
methods: read
action:
- target: py2
weight: 100
- condition:
path: /v2*
methods: read
action:
- target: py3
weight: 100
- target: py2
weight: 0
```
> Add per-path targets for ALB

- graphql-schemas/schema.yml
- schemas/app-sre/pipelines-provider-1.yml
- schemas/app-sre/saas-file-2.yml
- schemas/app-sre/tekton-object-template-1.yml
- schemas/app-sre/tekton-provider-defaults-1.yml
- schemas/openshift/deploy-resources-1.yml
The choice here is to have mandatory defaults that cover for everything a
tekton provider needs and let the pipeline provider redefine whatever it
needs.  In this way we don't need to do hardcode any field in
qontract-reconcile outside of the graphql query as we know that all providers
will always have everything from the defaults.
Part of [APPSRE-4165](https://issues.redhat.com/browse/APPSRE-4165)
> Add support for pipeline provider defaults

- graphql-schemas/schema.yml
- schemas/app-sre/pipelines-provider-1.yml
We will make sure that all pipelines providers always have what they need
to work properly and will fail at a schema level without the need of any
ad-hoc checks in the the code.
This is a breaking change.
part of APPSRE-4165
> Make tekton provider defaults mandatory

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
New optional enum field `type` within `ClusterNetwork_v1`.
Default will be `OpenShiftSDN`, handled in qontract-reconcile: https://github.com/app-sre/qontract-reconcile/pull/2099
> APPSRE-4229 cluster network type support

- schemas/dependencies/dyn-traffic-director-1.yml
Dyn requires a weight of  `1..255` so this limits the schema such that validation will fail early
> dyn-traffic-director: set range for record weight

- .gitignore
- Makefile
- dockerfiles/Dockerfile.test
- pr_check.sh
- test/conftest.py
- test/test_sql_regexp.py
- test/utils.py
- tox.ini
## Overview 
This PR adds test cases to ensure the sql-query regex validates the queries allowed in by the schema. The code also introduces a helper function to get validators for any other object that might need testing.
This is part of APPSRE-3316 to improve the sql queries regexp to allow comments on them. 
* Running these tests here instead of in app-interface it's faster and it provides a more direct way to test the expressions.
* A possible approach is to generate fake data and use qontract-validator, but it introduces a lot of boilerplate files/data.
> Add tests for SQL query regular expression

- graphql-schemas/schema.yml
- role names are now unique and searchable
**Test**
local bundle run with latest master from `app-interface`
```
qontract-server$ make bundle 
latest: Pulling from app-sre/qontract-validator
Digest: sha256:32fa05f3aeb43ae55d2b6db2f16eb99effaf1bab37863c42fbfaf0af50dbb552
Status: Image is up to date for quay.io/app-sre/qontract-validator:latest
quay.io/app-sre/qontract-validator:latest
mkdir -p /home/fishi0x01/Workspaces/redhat/app-sre/qontract-server/bundle
WARNING: We can't validate resource with schema /insights-prod/prometheus/prom.prometheusrules.yaml
WARNING: We can't validate resource with schema /insights-stage/prometheus/prom.prometheusrules.yaml
WARNING: We can't validate resource with schema /observability/prometheusrules/hive-stage-capacity.prometheusrules.yaml
WARNING: We can't …
```
> APPSRE-4164 make roles unique and searchable

- schemas/common-1.json
- test/test_sql_regexp.py
This PR improves the sql validator pattern adding the following capabilities. 
Jira: APPSRE-3316
* Add comments to queries with the `/* [comment] */` format. `--` at the end of line is not supported 
* `explain analyze select` is now supported. A tenant might require to use this statement to evaluate costs, etc. 
The regexp restricts the usage of `explain analyze` to use just `select` statements
> Improve sql query validator pattern

- schemas/aws/elasticsearch-defaults-1.yml
part of [APPSRE-4219](https://issues.redhat.com/browse/APPSRE-4219)
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#advanced_security_options
> Added AWS ES advanced security options support

- schemas/openshift/prometheus-rule-1.yml
Currently, we are unable to implement an alert on our query path SLOs as `query` is not a permitted label in the Prometheus rule schema.
Read path latency measurements are identified by the (namespace, query, latency) tuple. See [these](https://prometheus.app-sre-stage-01.devshift.net/graph?g0.expr=(latencytarget%3Aup_custom_query_duration_seconds%3Arate1d%7Blatency%3D%222.0113571874999994%22%2Cnamespace%3D%22observatorium-mst-stage%22%2Cquery%3D%22query-path-sli-1M-samples%22%7D%20%3E%20(3%20*%200.9)%20and%20latencytarget%3Aup_custom_query_duration_seconds%3Arate2h%7Blatency%3D%222.0113571874999994%22%2Cnamespace%3D%22observatorium-mst-stage%22%2Cquery%3D%22query-path-sli-1M-samples%22%7D%20%3E%20(3%20*%200.9))%20or%20(latencytarget%3Aup_custom_query_duration_seconds%3Arate3d%7Blatency%3D …
> Add query to permitted Prometheus rule labels.

- schemas/openshift/cluster-1.yml
the expected result is that terraform resources will be reconciled regularly and output resources will not be applied to disabled clusters.
> allow disabling terraform-resources per cluster

- graphql-schemas/schema.yml
- schemas/app-sre/app-1.yml
Make it possible to display multiple Grafana Urls for a given service
This implements requirements for configuring multiple dashboards, as described in this ticket: https://issues.redhat.com/browse/APPSRE-3494
Corresponding update in visual qontract: https://github.com/app-sre/visual-qontract/pull/149
> Grafana Urls as list

- graphql-schemas/schema.yml
- schemas/openshift/terraform-resource-1.yml
related to https://issues.redhat.com/browse/OSD-8770
required for https://github.com/app-sre/qontract-reconcile/pull/1962
this PR adds schemas required to support a new terraform-resources provider: `route53-zone`
> [terraform-resources] add schemas for route53-zone

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
part of https://issues.redhat.com/browse/APPSRE-4092
to be able to create vpc peerings without OCM using the account-vpc provider.
> [terraform-vpc-peerings] add support to provide role to assume for account-vpc

- graphql-schemas/schema.yml
- schemas/app-interface/app-interface-settings-1.yml
we currently store the smtp settings in the qontract-reconcile toml file.
this PR adds schema support to specify smtp settings in app-interface settings.
required for https://github.com/app-sre/qontract-reconcile/pull/2157
> add smtp settings to app-interface settings

- graphql-schemas/schema.yml
- schemas/dependencies/github-org-1.yml
in case an integration needs to use a token, with no regards to what account it is from, with this PR we can define a default org to be used.
> add default field to github org

- graphql-schemas/schema.yml
**Motivation**
We want to simulate multiple accounts in test runs. For that reason, we must be able to allow multiple account aliases to point to the same AWS `uid`.
Decision for this change: https://issues.redhat.com/browse/APPSRE-4399
**Changes**
Remove uniqueness constraint from `uid`
**Test**
Successfully bundled with schema multiple accounts in app-interface locally.
> APPSRE-4339 AWS uid must not be unique

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
the purpose for VPC peerings is not always obvious. this change
introduces optional description fields to allow documentation
of VPC peering connections.
Ref: https://issues.redhat.com/browse/APPSRE-4428
> add description field to VPC peering connections

- README.md
- graphql-schemas/schema.yml
- schemas/openshift/terraform-resource-1.yml
This adds `publish_log_types` to the schema. The types will be consumed in a next step by our terraform integration to forward logs to cloudwatch loggroups accordingly.
Usage example:
```
terraformResources:
- provider: elasticsearch
account: xxx
identifier: kibana-elasticsearch
output_resource_name: kibana-elasticsearch
publish_log_types:
- ES_APPLICATION_LOGS
- SEARCH_SLOW_LOGS
```
Tested locally by adding following to one of our existing services in app-interface:
```
- provider: elasticsearch
...
publish_log_types:
- ES_APPLICATION_LOGS
- SEARCH_SLOW_LOGS
```
Then run:
```
app-sre/qontract-server$ make dev 
...
WARNING: We can't validate resource with schema ...
[]
yarn run v1.22.17
$ node ./dist/main-bundle.js
2022-01-25T17:17:57.599Z INFO: Running at http://localhost:4000/graphql …
```
> APPSRE-4119 add publish_log_types list for ES

- graphql-schemas/schema.yml
- schemas/openshift/terraform-resource-1.yml
following https://github.com/app-sre/qontract-reconcile/pull/1962 where we added support for dns zones, we need to be able to provision resources with names that includes dots.
> route53-zone add name field

- graphql-schemas/schema.yml
- schemas/aws/account-1.yml
- schemas/aws/sharing-option-1.yml
part of https://issues.redhat.com/browse/APPSRE-4621
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/34669
this PR adds support to define `sharing` between aws accounts. we use the provider pattern to allow future sharing options between aws accounts.
this `sharing` option is defined on the source account.
example:
```
$schema: /aws/account-1.yml
name: source
...
sharing:
- provider: ami
account:
$ref: /aws/destination/account.yml
regex: '^.*$'
```
> add aws sharing options

- graphql-schemas/schema.yml
- schemas/dependencies/dns-zone-1.yml
part of https://issues.redhat.com/browse/APPSRE-4705
similar to using `_target_cluster` to obtain the elb fqdn, we can target a namespace with a `route53-zone` provisioned in it to automatically obtain NS records of that zone (instead of hard coding them).
example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/35369
> [terraform-aws-route53] add support for target namespace zone

- graphql-schemas/schema.yml
- schemas/app-interface/app-interface-settings-1.yml
**Motivation**
We currently store configuration for the `github-repo-invites` integration in our `config.toml`. This PR adds a schema to move the `[github-repo-invites]` toml section to our `app-interface` repo.
**Test**
Successfully ran:
```
make bundle
```
Further, tested with `--dry-run` in corresponding [q-r PR](https://github.com/app-sre/qontract-reconcile/pull/2239) in qontract-reconcile
> APPSRE-4404 schema for githubRepoInvites

- graphql-schemas/schema.yml
- schemas/dependencies/endpoint-monitoring-provider-1.yml
following the provider pattern for endpoint monitoring established in the [endpoint monitoring design doc](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/service-endpoint-monitoring.md), this schema change adds signalfx metric scraping capabilities using https://github.com/geoberle/signalfx-prometheus-exporter
since signalfx can be a metric store for arbitrary metric producing systems like catchpoint, the integration following this schema change will open a way to get ahold of those metric sources in a generic way.
similar to the blackbox exporter provider, this implementation acquires metrics by scraping
an endpoint that returns target specific metrics. while the target for blackbox-exporter is usually
a URL, for signalfx it is a label/value …
> add signalfx as endpoint monitoring provider

- graphql-schemas/schema.yml
**Motivation**
We want to be able to query users based on their `org_username`. 
This is a requirement for https://github.com/app-sre/qontract-reconcile/pull/2263
**Test**
Tested with corresponding feature branch in q-r https://github.com/app-sre/qontract-reconcile/pull/2263
> APPSRE-3652 make org_username searchable

- graphql-schemas/schema.yml
**Motivation**
I would like to be able to query a cluster by name for https://github.com/app-sre/qontract-reconcile/pull/2263
This PR enforces uniqueness on cluster names.
**Test**
schema bundles, i.e., there are no duplicate cluster names as of now.
> APPSRE-3652 make cluster name searchable

- schemas/app-sre/saas-file-2.yml
Relates to: https://issues.redhat.com/browse/APPSRE-4642
I suspect we may still have Q-R problems by doing just this and removing the Slack property from saas-files, but starting with this to see where get in fedramp.
> make slack optional for saas-file-2 files

- graphql-schemas/schema.yml
- schemas/dependencies/jira-board-1.yml
- schemas/dependencies/jira-severity-priority-mappings-1.yml
part of https://issues.redhat.com/browse/APPSRE-4750
to be able to dynamically generate jiralert configuration that works for every jira board, we need to know which board uses which priorities.
> alert severity ticket priority mappings

- schemas/app-interface/app-interface-settings-1.yml
- schemas/app-interface/credentials-request-1.yml
to be able to use credentials-sender as a way to send vault content.
> remove credentials name enum

- graphql-schemas/schema.yml
- schemas/aws/s3-1.yml
- schemas/openshift/terraform-output-format-1.yml
- schemas/openshift/terraform-resource-1.yml
Provide an output_format section to /openshift/terraform-resource-1.yml. This section will hold configuration data to drive the formatting process for terraform output data. output_format configuration is provider based, allowing different implementations to format the terraform outputs into consumable kubernetes secrets.
The first supported provider is the generic-secret provider, which formats the terraform output data as a kubernetes secret in the exact same way as it was handled before this change. to influence the output format, the secret data section can be specified inline, while providing jinja2 templating functionality.
The generic-secret provider will be the implicit default one when none is specified, making the following three declarations equivalent:
```yaml …
```
> generic-secret output_format for terraform based output secrets

- graphql-schemas/schema.yml
- schemas/common-1.json
- schemas/dependencies/status-page-component-1.yml
- schemas/dependencies/status-provider-1.yml
this schema change is based on the design doc https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/36105
it proposes a provider based status management approach for status page components,
specifically the following two providers will be enabled by this change
* prometheus-alerts - set the status page component status based on prometheus alerts
* manual - set the status page component status statically via app-interface
In the following example, the status of the component is Under Maintenance until the defined timestamp in manual.until has passed. After that, the status is managed based on Prometheus alerts.
```yaml
---
$schema: /dependencies/status-page-component-1.yml
name: yakk-shaving-service
...
status:
- provider: manual
manual:
until: timestamp-with-timezone …
```
> [statuspage] add schema capabilities to manage a component status

- README.md
- graphql-schemas/schema.yml
- schemas/access/role-1.yml
- schemas/app-sre/saas-file-1.yml
This reverts commit a61aafb1efe37bc63324a68d5eebad2354c5993d.
Apparently there are still issues in the `github` integration with saas-file-1
```
gql.transport.exceptions.TransportQueryError: {'message': 'Cannot query field "saasFiles" on type "App_v1". Did you mean "saasFilesV2"?', 'locations': [{'line': 15, 'column': 5}], 'extensions': {'code': 'GRAPHQL_VALIDATION_FAILED'}}
```
> Revert "APPSRE-3556 deprecate saas-file-1 (#125)"

- schemas/app-sre/sre-checkpoint-1.yml
We have added a contract version to every checkpoint file in
app-interface. We can now make it mandatory
Part of APPSRE-4788
Signed-off-by: Rafael Porres Molina <rporres@gmail.com>
> Make contract version mandatory in checkpoint file

- graphql-schemas/schema.yml
- schemas/vault-config/instance-auth-1.yml
ticket: https://issues.redhat.com/browse/APPSRE-4506
Vault api returns slightly different payloads when reading secrets from kv v1 vs v2. This needs to be handled within vault-manager logic, and therefore requires defining which secret engine version the particular secret is within.
> add secret engine attribute for vault instance auth

- graphql-schemas/schema.yml
- schemas/app-interface/query-validation-1.yml
part of https://issues.redhat.com/browse/APPSRE-5561
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/schema-compatibility.md
To avoid breaking tenants' automations that rely on app-interface, we need to make app-interface aware of the queries tenants are using in their automations. Differently worded, tenants should be able to declare queries they are using and request to be notified for breaking changes.
For that purpose, we will introduce a new schema, `query-validation-1`, which will include the common fields, such as `name` and `description`. In addition, it will include a `queries` field.
This field will be a list of references (paths) to resources (files under the `resources/` directory) which are a file containing a graphql …
> add schemas for query-validation

- graphql-schemas/schema.yml
- schemas/app-interface/app-interface-settings-1.yml
this will allow us to provide relative links to files if we wish.
currently planned to be used for:
https://github.com/app-sre/qontract-reconcile/pull/2422/files#diff-0e7b34d72a912959fc73360c9ad81c9ce8d1ca4fff2ef4dac354f976728de183R1389
making this field mandatory, mostly because it is a very simple change.
> add required repo url field to settings

- schemas/openshift/prometheus-rule-1.yml
In our recent [incident](https://coreos.slack.com/archives/C03GBPGV52B) our API Write Path SLO alerts failed to fire when they should have fired.
This is because we were pruning the `code` [label](https://github.com/rhobs/configuration/blob/14d4991acebe4aea041d05fdf6f900db6e3a5ddc/observability/prometheusrules.jsonnet#L128) in order to pass the App-Interface MR checks. 
This PR adds `code` as a permitted label in the prometheus rule app-interface schema.
Signed-off-by: Ian Billett <ibillett@redhat.com>
> MON-2563: Add 'code' to permitted prometheus rule label schema

- graphql-schemas/schema.yml
- schemas/aws/account-1.yml
- schemas/aws/terraform-state-1.yml
- schemas/dependencies/terraform-state-1.yml
Part of [APPSRE-4516](https://issues.redhat.com/browse/APPSRE-4516)
Goal is to have a separate yaml file within app-interface that is then referenced in the account.yml file:
```
---
$schema: /dependencies/terraform-state-1.yml
provider: s3
bucket: someBucket
region: someRegion
integrations:
- integration: terraform-resources
key:  qontract-reconcile.tfstate
- integration: terraform-tgw-attachements
key: qontract-reconcile-tgw-attachments.tfstate
```
Within some-cloud-account.yml:
```
...
terraformState:
$ref: /aws/app-sre-stage/tf-state-test.yml
```
For app-sre, we have specific terraform integrations for route53, resources, tgw, users, and vpc peerings
Signed-off-by: Suzana Nesic <snesic@redhat.com>
> creating new schema for tf state

- schemas/aws/terraform-resource-2.yml
- schemas/openshift/terraform-resource-1.yml
We should always add every instance class option for the family.
> Add missing instance classes for db.m5, db.r5, db.m6g

- schemas/openshift/external-resource-1.yml
part of https://issues.redhat.com/browse/APPSRE-5711
it is beyond me what is causing the need to have this, but it makes https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/40170 work.
happy if someone can explain.
the problem without this is `SCHEMA_DEFINITION_NOT_FOUND`
> add crossrefs to top level schema

- schemas/app-sre/saas-file-2.yml
- schemas/app-sre/vault-secret-parameter-1.yml
- schemas/common-1.json
`openshift template parameter name` requirements are not well documented but we now that hypens don't work
this change introduces a pattern for secret parameter names that allows only characters (upper,lower), numbers and underscores. also, they need to start with a character
update: also make sure saas parameter names adhere to the pattern
> [saas file] secretParameter names can't contain dashes

- graphql-schemas/schema.yml
- schemas/app-sre/integration-spec-1.yml
the `shardingStrategy` will be used by the integrations-manager to statically or dynamically deploy shards for integrations.
the `static sharding` strategy is the backwards compatible default strategy that deploys shards based on `spec.shards`
the `per-aws-account` deploys shards based on the aws accounts in app-interface
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/qontract-operator-sharding.md
part of: https://issues.redhat.com/browse/APPSRE-2963
> add shardingStrategy for integrations

- schemas/aws/terraform-resource-2.yml
- schemas/openshift/external-resource-1.yml
part of https://issues.redhat.com/browse/APPSRE-5726
depends on https://github.com/app-sre/qontract-validator/pull/38
following the validator PR, we can define `oneOf` for `refs`.
we also move the s3 definition into terraform-resource-2 because it can not be reused (terraform-resources-2 does not require an `account`).
> fix s3 schemas for external resources

- graphql-schemas/schema.yml
- schemas/app-interface/query-validation-1.yml
- schemas/aws/terraform-resource-2.yml
- schemas/common-1.json
- schemas/dependencies/jenkins-config-1.yml
- schemas/openshift/openshift-resource-1.yml
Introduce a common type declaration `/common-1.json#/definitions/resourceref` that is compatible with `string` but represents a path to a resource.
```yaml
---
"$schema": /metaschema-1.json
version: '1.0'
type: object
...
properties:
...
path:
"$ref": "/common-1.json#/definitions/resourceref"
```
This information is used in `qontract-validator` to verify resource references and enables fast fail for PR checks during bundle creation. At the same time it is compatible with current data.
Additionally add a property `isResourceRef = true` to the respective field in the graphql schema. This can leveraged during schema introspection.
During bundle creation, `resources.backrefs` will be filled with a list of data files that reference a resource.
References:
* design doc …
> explicit resource reference metadata in qontract-schema data files

- graphql-schemas/schema.yml
- schemas/app-interface/app-interface-sql-query-1.yml
Part of [APPSRE-3787](https://issues.redhat.com/browse/APPSRE-3787), this adds a `delete:` parameter for CronJob SQL queries so that they can be removed after being created in an automated manner.
> Delete field for SQL Query - APPSRE-3787

- schemas/aws/elasticsearch-defaults-1.yml
Add an `auth` section for TF managed ES domains.
This is the beginning of transitioning all existing ES domains towards an auth scheme. Thus, this change is fully backwards compatible with existing ES domains.
Once migration with existing ES domains is done, we will:
- make `auth` section a requirement.
- remove `advanced_security_options` block. For compliance reasons this is not a free customer choice any longer.
> APPSRE-3409 add auth section for ES defaults

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
- schemas/openshift/jump-host-1.yml
this will allow us to define the jump host once instead of duplicating the lines between all cluster files.
> extract jump host to its own schema

- schemas/app-sre/app-1.yml
Following contract changes, we want this to be a read-only markdown
document. We currently cannot enforce it via a regex
because we still have a lot of TODOs and some docs in google.
> Change description of architectureDocument

- graphql-schemas/schema.yml
PR checks can fail a lot faster if the uniqueness is enforced on the schema and detected during bundling instead of a dry run of the integration
ref: https://issues.redhat.com/browse/APPSRE-5973
> make app-interface-sql-query name unique

- graphql-schemas/schema.yml
- schemas/app-interface/graphql-schemas-1.yml
this `resolveResource` flag enables the resolution of resource ref fields during query time.
this change also deprecates the `isResourceRef` flag. `isResource` is metadata enough to determine if a field is a resource. the nuance to determine if a field is a direct resource or just a reference to it, can be done with the field type, e.g. string vs Resource_v1
see https://github.com/app-sre/qontract-server/pull/147 for the qontract-server change
ref: https://issues.redhat.com/browse/APPSRE-5950
> add resolveResource flag to graphql schema types

- graphql-schemas/schema.yml
- schemas/access/permission-1.yml
to allow populating gitlab groups based on pagerduty schedules.
think @app-sre-ic, but in an app-interface merge request.
> add pagerduty reference to gitlab-membership permissions

- graphql-schemas/schema.yml
this enables writing queries for jenkins-config-1.config_path like
```
{
jenkins_configs: jenkins_configs_v1 {
name
...
type
config
config_path {
content
}
}
}
```
part of https://issues.redhat.com/browse/APPSRE-6003
follows up on https://issues.redhat.com/browse/APPSRE-5950
> enable resource resolution on jenkins-config.config_path

- schemas/app-sre/saas-file-2.yml
depends on https://github.com/app-sre/qontract-validator/pull/41
follows up on #199
with this change, saas file targets can either be inlined or referenced.
this change introduces an issue for `saas-file-owners`, such that tenants will not be able to lgtm their own promotions. i'd like to merge this and work on a PoC to make it feasible. before that happens, we will not allow this usage for tenants.
> allow saas file target to be inlined or referenced

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
* Add schema support for creating SNS topics
* Add schema support for creating  RDS event subscription to SNS topics
We want to provide tenants the ability to be able subscribe to email notifications about their RDS instances's activity. 
Design doc [here](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/rds-upgrades-and-maintenance.md#database-maintenance-notifications).
* Running terraform-resources integration through dry-run mode and check the output consistent with the yml defined in open source App Interface.
* Running the integration without dry-run mode against ter-int-dev AWS account and was able to see SNS topics and RDS event subscriptions created( and deleted) as intended.
yml that was used:
```
externalResources:
- provider: aws …
```
> Add schema support for creating SNS topics and RDS event notification

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-2.yml
to allow full self-service over saas file secretParameters, we still want to control the paths of the secrets that will be used.
with this schema, we enable defining a list of strings which are paths that are allowed.
as long as secret parameters are added/updated within the allowed path, we enable full self-service.
> add allowed secret parameter paths

- graphql-schemas/schema.yml
- schemas/app-sre/app-1.yml
with this change, we enable the definition of roles per repos. users who have these roles will not be prohibited from adding labels.
this is to handle users with Developer access adding labels to MRs.
> enable support for gitlab-housekeeping to only accept labels from users in specific roles

- graphql-schemas/schema.yml
- schemas/app-sre/integration-1.yml
the flag `/app-sre/integration-1.yml#pr_check.early_exit` controls if an integration will exit early from the potentially long running PR check dry-run if it can detect that there has been no change in desired state. the integration needs to support early exit, otherwise the flag has no effect.
q-r change: https://github.com/app-sre/qontract-reconcile/pull/2672
part of: https://issues.redhat.com/browse/APPSRE-6098
```yaml
$schema: /app-sre/integration-1.yml
name: terraform-vpc-peerings
pr_check:
cmd: terraform-vpc-peerings
early_exit: true
```
> [integration] early exit feature for pr-check dry runs

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
- schemas/app-interface/graphql-schemas-1.yml
introduce a generic interface `DatafileObject_v1` all datafile types automatically implement (in additional to potential other interfaces they declare). the assignment of the interface to datafile types happens automatically during bundle loading in `qontract-server`. object resolution during query time is achieved by the `interfaceResolve.strategy = schema` strategy based on the `datafile` defined for a type. this type enables mixed-type fields in graphql types where various types can be assigned.
this generic interface can be used to collect all kinds of objects in a list. 
first usecase will be declaring ownership for datafiles.
```yaml
---
$schema: /access/role-1.yml
...
self_service:
- description: AppSRE services
datafiles:
- $ref: /services/github-mirror/cicd/deploy.yaml
- $ref: …
```
> resource and datafile ownership

- graphql-schemas/schema.yml
- schemas/dependencies/jira-board-1.yml
Some jira boards don't have default `To Do` state. This change allows us to define reopen state per jira board. 
Setting correct value will result into successful Jira API calls, thereby reducing the no of calls to Jira (because Alertmanager loves to retry on 500 errors)
Related:[ APPSRE-5712](https://issues.redhat.com/browse/APPSRE-5712)
> add issue reopen state

- schemas/aws/elasticsearch-defaults-1.yml
partly revert https://github.com/app-sre/qontract-schemas/pull/221
gp3 and throughput dose not supported by terraform aws provider 3.75.2
> remove throughout for ebs_options

- graphql-schemas/schema.yml
- schemas/openshift/openshift-resource-1.yml
related to https://issues.redhat.com/browse/APPSRE-6098
to speed up openshift-resources (and prometheus-rules-tester) early-exit, we need to skip as many resources as possible.
resources with dynamic content (generated based on graphql query results) must be checked, but only them.
with this field, we will know exactly the ones to check. we will add a validation that if the query() function is used, this option must be set to true.
> add support to enable query support

- graphql-schemas/schema.yml
in order to improve performance for openshift-resources related integrations and their early-exit mode, their resources will be fetched inline along with the rest of the data instead of sequential reads.
it is crucial to align the rollout of this schema change with the qontract-reconcile integration using those fields (openshift-resources, openshift-routes, prometheus-rules-tester).
relates to https://issues.redhat.com/browse/APPSRE-6098
> resolvable resource references for openshift-resources

- graphql-schemas/schema.yml
- schemas/dependencies/dns-zone-1.yml
[APPSRE-6143](https://issues.redhat.com/browse/APPSRE-6143)
Currently, Route 53 DNS zones have a 1:1 correspondence between the domain name the route they are defined for, and their App Interface representation. This adds an optional `domain_name` field which lets you define a different `name` for the zone so that you can have two Route 53 Zones which refer to the same domain name but have different App Interface and Terraform identifiers. This is in order to support [split-view DNS](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-considerations.html#hosted-zone-private-considerations-split-view-dns).
QR change here: https://github.com/app-sre/qontract-reconcile/pull/2750
> Add domain_name option for DNS zones

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-2.yml
related to https://issues.redhat.com/browse/APPSRE-6021
saas file deprecation indicates a saas file is being deprecated. with qontract-reconcile implementation, this field being true may mean that a saas file can no longer receive updates, and users will be forced to migrate resources out of it. at the very least, we can output a deprecation message.
> introduce saas file deprecation

- graphql-schemas/schema.yml
- schemas/app-interface/graphql-schemas-1.yml
- schemas/app-sre/saas-file-target-1.yml
finding differences in datafiles is a complex task, especially when dealing with lists of objects, where objects don't have clear identities. diff libraries like pythons deepdiff do a great job at this, using heuristics to find out if an objects in a list was just moved to another place or if the object has really changed significantly. diff libraries can be further supported in yielding better results, by providing hints about what properties of an object have key characteristics within the context of the current list.
our current gql type declaration syntax supports uniqueness on single properties globally within a bundle with the `isUnique` flag.
within certain contexts, that is too restrictive or a single property can not even be used to establish uniqueness. therefore this PR …
> unique and identifiable objects within lists

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
- schemas/metaschema-1.json
Related: APPSRE-4798
This change adds a new field `old_parameter_group` that will be used during RDS upgrades. 
This MR also introduces usage of `dependencies` as defined in json-schema RFC https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-01#section-6.21
> [APPSRE-4798] Add old_parameter_group for rds provider

- graphql-schemas/schema.yml
depends on https://github.com/app-sre/qontract-server/pull/165
replaces #244
by adding this backref we are able to find roles referencing saas files in the `self_service` section:
```
{
saas_files_v2
{
name
selfServiceRoles{
name
}
}
}
```
> add backref from saas files to roles via self_service

- graphql-schemas/schema.yml
semantically this will imply that the context will be extracted from a changing file without condition.
in the following example, the missing `changes.context.when` field means that this change-type becomes active whenever
* a namespace file is created on a cluster this change-type is bound to
* a namespace file is deleted from a cluster this change-type is bound to
* a namespace file belgong to a cluster is changed
the changes allowed in the namespace file still depend on the jsonpath expressions listed under `changes.jsonPathSelectors`
```yaml
changes:
- provider: jsonPath
changeSchema: /openshift/namespace-1.yml
jsonPathSelectors:
- $
context:
selector: cluster.'$ref'
when: null
```
> make the change-type context.selector when condition optional

- README.md
- graphql-schemas/schema.yml
- schemas/access/role-1.yml
depends on https://github.com/app-sre/qontract-reconcile/pull/2805
once the reconcile PR was promoted, the removal of `owned_saas_files` from the schemas may be promoted as well (this PR).
> deprecate owned_saas_files

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
related to https://issues.redhat.com/browse/APPSRE-4709
with this list in place, we can add a validation that cluster upgrade policies are only using a workload name from this list.
this will help us avoid adding a "hard coded" enum to the schemas repo, which is AppSRE specific.
> add enum for upgrade policy allowed workloads

- schemas/openshift/prometheus-rule-1.yml
We (RHOBS) team are in the process of introducing SLOs for Rules API and Observatorium Alertmanager. 
We are now in the process to deploy alerts to stage on the related SLOs (see draft MR: [!48083](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/48083#8ad0a2beb2c177328d8b5e82470f38992db62fea_902_1061))
We would like to add a `method` label to the prometheus schema in order to better group some of our alerts (alert example with mentioned label [here](https://github.com/rhobs/configuration/blob/main/resources/observability/prometheusrules/rhobs-slos-mst-stage.prometheusrules.yaml#L904-L920))
Signed-off-by: Jéssica Lins <jessicaalins@gmail.com>
> Add method label to prometheus schema

- graphql-schemas/schema.yml
- schemas/app-interface/query-validation-1.yml
related to https://issues.redhat.com/browse/APPSRE-4709
query-validator currently only validates that queries are executed successfully.
with the addition of `resources`, we can do everything we already can in `openshiftResources` (jinja2 for example). with this addition, we can validate the actual data, and not only the query results.
logic added in https://github.com/app-sre/qontract-reconcile/pull/2807
> add option to validate resources with queries

- schemas/aws/asg-defaults-1.yml
[APPSRE-6297](https://issues.redhat.com/browse/APPSRE-6297)
Add support for max_instance_lifetime for AWS auto-scaling groups. Such that image builder workers can be ephemeral in nature. 
QR change: https://github.com/app-sre/qontract-reconcile/pull/2839
> [ASG] Add max_instance_lifetime option

- schemas/app-sre/saas-file-target-1.yml
following up on https://issues.redhat.com/browse/APPSRE-4535, we no longer need to deploy from the quayio branch.
> remove quayio from allowed refs

- schemas/aws/rds-defaults-1.yml
Related: APPSRE-5597
Per https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#auto_minor_version_upgrade
`auto_minor_upgrade_version` defaults to true if not specified explicitly.
This takes care of some RDS instances which refer to such defaults with no `auto_minor_upgrade_version` by having us to define it explicitly but limit it with the change introduced in https://github.com/app-sre/qontract-schemas/pull/264
> APPSRE-5597: make auto_minor_version_upgrade parameter as required so we can set it explicitly with false value

- Makefile
- pr_check.sh
[APPSRE-6368](https://issues.redhat.com/browse/APPSRE-6368)
On PR checks of schema updates, bundle up all the schema information without any A-I data and then run an instance of qontract-server to check whether there are any issues with the GraphQL Schema. 
Output on successful run with valid GQL schema:
```
rm -rf fake_data fake_resources
[]
yarn run v1.22.19
warning Skipping preferred cache folder "/opt/app-root/src/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1001".
$ node ./dist/main-bundle.js
2022-10-05T19:44:47.374Z INFO: loading initial bundle 76cd257364365fbe2fe72feab840654aebcf87ca3afc3fb96ae0997dfe02dd95
2022-10-05T19:44:47.489Z INFO: Running at http://localhost:4000/graphql
(node:16) [DEP0152] …
```
> [APPSRE-6368] Validate GQL Queries on PR Checks

- schemas/app-sre/integration-spec-1.yml
This MR adds googleChat as a boolean logging output option, supporting: https://github.com/app-sre/qontract-reconcile/pull/2801,  https://github.com/app-sre/fluentd/pull/4
> Add googleChat as a logging output option for integration specs

- graphql-schemas/schema.yml
- schemas/app-interface/change-type-1.yml
this flags will allow temporary deactivation of a change-type. a disabled change-type will not enable self-service anymore but will still log to the PR check logs.
this can be used to
* disable a buggy change-type
* analyze change-type decisions in production while not affecting production (especially useful while developing a new change-type)
> disabled flag for change-types

- graphql-schemas/schema.yml
- schemas/app-interface/app-interface-settings-1.yml
- schemas/app-sre/app-1.yml
[APPSRE-6355](https://issues.redhat.com/browse/APPSRE-6355)
* To increase visibility of MRs for ICs in AppSRE, this allows us to define additional repos to watch for MRs
* The watched repos must be on GitLab.cee and [managed by the AppSRE Bot](https://gitlab.cee.redhat.com/service/app-interface#enable-gitlab-features-on-an-app-interface-controlled-gitlab-repository) as well as have a PR check job setup
* Corresponding QR change here: https://github.com/app-sre/qontract-reconcile/pull/2852
Example of an updated app file:
```yaml
codeComponents:
- name: infra
resource: other
url: https://gitlab.cee.redhat.com/app-sre/infra
showInReviewQueue: true
gitlabHousekeeping:
enabled: true
rebase: false
jira:
$ref: /dependencies/jira/issues-redhat-com.yaml
```
> [APPSRE-6355] Add review repos to App Interface settings

- schemas/app-interface/prometheus-rule-test-1.yml
This PR changes the Prometheus rule test schema `exp_samples` under `promql_expr_test` to accommodate floating points instead of just integers, as a series sample can be a float.
> Change prometheus rule test schema for floats

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
This adds the dns-zone-1 schema to the list of allowed datafiles types that can be self services
This is needed for the [corresponding](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/50067) MR which adds the definition
> add dns-zone-1 to self-service datafiles enum

- graphql-schemas/schema.yml
- schemas/app-interface/change-type-1.yml
this is a proposal to implement change-type inheritance, where one change-type can reference other change-types and get their permissions as well.
this may help us prevent duplication between change-types where we want to include the same permissions and will provide reusability of change-types.
part of: https://issues.redhat.com/browse/APPSRE-6473
> change-type inherritence

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
- schemas/app-sre/scorecard-2.yml
part of https://issues.redhat.com/browse/APPSRE-6506
following up on v1 in #280
this PR introduces v2, which replaces the hard coded AC fields with a list of items with a `name` property.
the name is limited by an enum, a length definition and a uniqueness constraint, to guarantee all ACs are covered in a report.
> Scorecard v2

- graphql-schemas/schema.yml
- schemas/app-interface/deletion-approval-1.yml
- schemas/aws/account-1.yml
- schemas/cloudflare/account-1.yml
part of https://issues.redhat.com/browse/APPSRE-6478
This renames the `AWSAccountDeletionApproval_v1` schema to a more generic name `DeletionApproval_v1` and adds it to the `CloudflareAccount_v1` schema
The object definition for a `deletionApproval` is also extracted out of AWS and Cloudflare accounts schemas into a common definition
This is required by https://github.com/app-sre/qontract-reconcile/pull/2896
> add deletionApprovals for Cloudflare accounts

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
part of https://issues.redhat.com/browse/APPSRE-2494
with this change, we can switch OCM auth from a user to a ServiceAccount (implemented in https://github.com/app-sre/qontract-reconcile/pull/2905)
> add access token client secret field to OCM org

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
part of https://issues.redhat.com/browse/APPSRE-2494
deprecating `offlineToken` following up on #292, along with the promotion of https://github.com/app-sre/qontract-reconcile/pull/2905
> remove offlineToken

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
- schemas/openshift/openshift-cluster-manager-1.yml
part of https://issues.redhat.com/browse/APPSRE-6517
with this change, we can define a very lean list of clusters in an ocm file. this list will suffice to manage cluster upgrade schedules with an integration much like `ocm-upgrade-scheduler`.
> prepare to enable upgrade scheduling for ocm orgs

- graphql-schemas/schema.yml
- schemas/dependencies/dns-zone-1.yml
[APPSRE-6393](https://issues.redhat.com/browse/APPSRE-6393)
`unmanaged_record_names` in the `dns-zone-1.yml` schema is no longer needed as Terraform won't overwrite existing DNS records and only modifies records explicitly outlined in dns zone files. This MR removes that attribute from the schema and GQL.
> Remove unmanaged_record_names field from DNS zone schema

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
part of https://issues.redhat.com/browse/APPSRE-6517
in order to keep `upgradePolicyClusters` up-to-date with clusters being created/deleted, we need to define conditions of clusters (ClusterDeployment labels a.k.a external configuration labels) based on which we select an upgrade policy for a discovered cluster.
the intention is to create a separate integration that will submit MRs to app-interface to update `upgradePolicyClusters`, so we can keep the logic of `ocm-upgrade-scheduler-org` unchanged. the reason is that the current "static" nature of defining clusters is a no-go for management of OSD-FM fleets.
the OSD FM requirements are more complex compared to a regular customer, which usually has a single OCM org in a single OCM environment with a `statically managed set of clusters.
> [ocm-upgrade-scheduler-org] enable support for dynamic cluster discovery

- graphql-schemas/schema.yml
- schemas/cna/experimental-provisioner-1.yml
- schemas/openshift/external-resource-1.yml
CNA is being spiked. Renaming provisioner to `experimental` to highlight this must not be used in production.
> APPSRE-6295 mark CNA provisioner as experimental

- graphql-schemas/schema.yml
- schemas/aws/account-1.yml
- schemas/cna/asset-1.yml
temporarily add support for the `example-aws-assumerole` CNA type.
```
- provider: aws-assume-role
identifier: test
aws_assume_role:
slug: test
account:
$ref: /aws/some-acc/account.yml
```
the role ARNs this and other kinds require, are stored in the `/aws/account-1.yml` schema. a default role ARN can be defined but module specific ones are supported as well. while we iterate we might drop support for the defaultRoleARN or revamp the way of providing module/context specific default parameters
```
---
$schema: /aws/account-1.yml
cna:
defaultRoleARN: arn:aws:iam::xxx:role/RH-CNA
moduleRoleARNS:
- module: aws-rds
arn: arn:aws:iam::xxx:role/RH-CNA-RDS
```
> cna assume-role resource

- schemas/aws/terraform-resource-2.yml
This was a safeguard against a bug which was present in an old provider version. we have since moved to a much newer version in which the bug has been fixed
> remove minItems property on ALB targets

- graphql-schemas/schema.yml
- schemas/app-sre/app-1.yml
Adds support for specifying partitioned gitlab instance to copy repositories to. https://github.com/app-sre/git-partition-sync-producer performs the graphql query to obtain the sync configuration.
ticket: https://issues.redhat.com/browse/APPSRE-6544
> Add attributes for gitlab sync support

- graphql-schemas/schema.yml
- schemas/cna/asset-1.yml
this is a first draft of the aws-rds CNA provider schema. it naively maps the fields required by the CNA module to a schema without considering concepts like `defaults` or `overwrites` for defaults as the `terraform-resources` flavour does.
```
- provider: aws-rds
identifier: cna-test-rds
vpc:
$ref: /aws/acc/vpcs/vpc.yml
defaults: /path/to/defaults.yml
overrides:
db_subnet_group_name: default
```
> CNA aws-rds provider

- graphql-schemas/schema.yml
Following up on !272 this adds googleChat as a logging parameter for FedRamp.
[APPSRE-6564](https://issues.redhat.com/browse/APPSRE-6564)
> Add googleChat to IntegrationSpecLogs_v1

- graphql-schemas/schema.yml
- schemas/cloudflare/account-1.yml
[APPSRE-6571](https://issues.redhat.com/browse/APPSRE-6571)
This is the schema needed for https://github.com/app-sre/qontract-reconcile/pull/2964 which allows setting 2FA enforcement on Cloudflare accounts via the account definition file
> add 2fa enforcement support to cloudflare account schema

- graphql-schemas/schema.yml
- schemas/cna/asset-1.yml
- schemas/cna/aws-assume-role-config-1.yml
- schemas/cna/aws-rds-config-1.yml
- schemas/cna/null-asset-config-1.yml
all CNA assets must have a `defaults` and an `overrides` section, as a lot of the terraform-resources do. the difference is, that each CNA type declares a special `XXXConfig_v1` type that is used for both fields.
```yaml
name: CNARDSInstance_v1
interface: CNAsset_v1
fields:
- { name: provider, type: string, isRequired: true }
- { name: identifier, type: string, isRequired: true, isUnique: true }
- { name: name, type: string }
- { name: defaults, type: CNARDSInstanceConfig_v1 } <--
- { name: overrides, type: CNARDSInstanceConfig_v1 } <--
```
having defaults following a strict schema and overrides being able to override all of the defaults, makes writing testable and verifiable code a lot easier.
> override and default schema represented by same schema objects

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
Breaking Change: The `cluster.auth` attribute is now a list and **required**
We want to support [multiple auth backends](https://issues.redhat.com/browse/APPSRE-6374) at the same time.
* [APPSRE-6374](https://issues.redhat.com/browse/APPSRE-6374)
* [APPSRE-6554](https://issues.redhat.com/browse/APPSRE-6554)
> cluster.auth attribute becomes a list of objects instead of a single object

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
This is a rework of #317, which was reverted. For the reviewer, nothing has changed compared to #317 
Breaking Change: The `cluster.auth` attribute is now a list and **required**
We want to support [multiple auth backends](https://issues.redhat.com/browse/APPSRE-6374) at the same time.
* [APPSRE-6374](https://issues.redhat.com/browse/APPSRE-6374)
* [APPSRE-6554](https://issues.redhat.com/browse/APPSRE-6554)
> cluster.auth attribute becomes a list of objects instead of a single object (#317)

- graphql-schemas/schema.yml
to be able to reference a datafile in a self-service role, it must inherently implement the `Datafile_v1` interface (think python protocol).
`Datafile_v1` requires a mandatory `path` attribute to be present, which usually makes sense for datafiles since they are actual files with a path in the filesystem of the bundle. `/app-sre/saas-file-target-1.yml` is different in the way that it is used as a datafile, but also inline. therefore the `path` field is optional in the case where it is used inline. graphql sees a conflict in this and does not allow the GQL type `SaasResourceTemplateTarget_v2` to be referencable in self service roles.
the trick is to come up with a second GQL type `SaasResourceTemplateTargetReference_v2` which is compatible with `Datafile_v1` and bind the `jsonschema` …
> [change-types] saas-file-target referencable in self-service role

- graphql-schemas/schema.yml
- schemas/cna/asset-1.yml
- schemas/cna/aws-rds-config-1.yml
- schemas/common-1.json
revert experiment where overrides and defaults are exactly the same schema. the result was that all fields in overrides and defaults needed to be optional so they can be used in both places without making overrides mandatory.
in this PR, overrides are now all optional, follow a schema in jsonschema but none in GQL where they are just JSON
> [cna] RDS overrides as json with all optional

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
Allow to reference an upgradepolicy template from OCM `upgradePolicyDefaults`.
This avoids repeating many time the same default for different labels such as `sector` (or region, or cluster-type, ...).
https://issues.redhat.com/browse/APPSRE-6595
Example usage: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/52219/diffs
> upgradePolicyTemplate in OCM upgradePolicyDefaults

- graphql-schemas/schema.yml
- schemas/dependencies/glitchtip-project-1.yml
glitchtip projects are now queried directly. updating a glitchtip project to have an `app` reference keeps app files leaner and follows similar conventions (see above backref)
> reference app from glitchtip project

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
- schemas/app-sre/app-1.yml
- schemas/dependencies/status-page-component-1.yml
similar to #335
instead of referencing status page components from an app file, we will reference the app from the statuspage component file.
this doesn't change much, but makes things consistent with other objects, like slo-document, scorecards, glitchtip projects, and more.
> reverse reference between app and statuspage component

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
[APPSRE-6549](https://issues.redhat.com/browse/APPSRE-6549)
Implementation PR: https://github.com/app-sre/qontract-reconcile/pull/3007
Allow to inherit cluster version data information from one org to an other. There are 2 fields: one on the publishing org and one on the one inheriting the data. This is to ensure both org owner agree to this data sharing.
> OCM org inheritance for cluster versions

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
prepare in advance for when we find a suitable permission to grant.
ideally we would remove this enum, but there is currently a technical limitation preventing it.
> self-service for more schema objects

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
Reverts app-sre/qontract-schemas#341
The OIDC related changes in qontract-reconcile and qontract-schemas break FedRAMP environment authentication. We have to revert and align on a strategy that can exist in parallel.
re: https://coreos.slack.com/archives/GGC2A0MS8/p1670432900179959
> Revert "OIDC IDP cluster auth object"

- graphql-schemas/schema.yml
- schemas/app-sre/pgp-reencrypt-settings-1.yml
Required for PGP re-encryption. This adds configuration options used by terraform-users and account-notifier integration. 
`skip_aws_accounts` setting might be removed in the future, once re-encryption was rolled out for all accounts. 
Related issue: https://issues.redhat.com/browse/APPSRE-4706
> APPSRE-4706 Add reencrypt PGP schema

- graphql-schemas/schema.yml
- schemas/app-interface/change-type-1.yml
For certain changes, the natural approvers can be found in the datafiles themselves and would not require explicit ownership via roles. To reduce the need for such explicit ownership, we can make change-types implicitly applicable on changes.
The following example enables users to approve updates on their `public_gpg_key`s. The `jsonPathSelector` is the mechanism to find a reference to an approver, either a `/access/user-1.yml` or `/access/bot-1.yml` object. In this example the selector is `$.path` which finds the approver in the changed file itself.
```yaml
$schema: /app-interface/change-type-1.yml
...
contextSchema: /access/user-1.yml
changes:
- public_gpg_key
implicitOwnership:
- provider: jsonPath
jsonPathSelector: $.path
```
https://issues.redhat.com/browse/APPSRE-6629
Signed-off-by: …
> [change-types] implicit ownership for change-types

- Makefile
- pr_check.sh
[APPSRE-6676](https://issues.redhat.com/browse/APPSRE-6676)
With the existing Makefile logic, it appears that Qontract Server is not run if `docker pull quay.io/app-sre/qontract-server` pulls a new version of the Qontract Server image. I'm not entirely sure why and troubleshoot using various different methods like splitting out to separate lines of the Makefile instruction but the issue persisted. Here, I'm splitting out the `docker pull` to a different Makefile instruction. Not 100% confident that this will fix the issue and it is difficult to test since the issue is so sporadic. However, I'll keep an eye on schemas checks and see if the behavior continues.
> [pr-check] Shell GQL Logic Update

- Makefile
- pr_check.sh
[APPSRE-6676](https://issues.redhat.com/browse/APPSRE-6676)
Move the timeout command to run within the container itself to avoid an issue where pulling the qontract-server container resulted in it not actually running.
> [pr-check] Move timeout into container

- schemas/dependencies/slack-workspace-1.yml
- schemas/openshift/cluster-1.yml
Prepare the `slack-usergroup` and `slack-cluster-usergroup`merge.
* `slack-usergroup` has to use `slack-workspace.integrations` to get channel for cluster user groups
* support `cluster.disable.integration` for `slack-usergroup`
Tickets:
* [APPSRE-6593](https://issues.redhat.com/browse/APPSRE-6593)
> slack-usergroup and slack-cluster-usergroup merge

- graphql-schemas/schema.yml
- schemas/app-interface/change-type-1.yml
Add a new change provider named `change-type` to `/app-interface/change-type-1.yml#changes.provider` that can reference an existing `change-type` and put it into the context of `changes.context`.
```yaml
- provider: change-type         <-- new provider
changeTypes:
- $ref: namespace-owner.yml   <-- puts the existing change-type ...
context:                      <-- ... into a new context
selector: app.'$ref'
```
This makes the referenced change-type usable in the ownership context of the referencing change-type. It redurced ownership management toil and makes the change-types reusable. It also enables the definition of higher level concepts for ownership, e.g. the owned entity is an app and by putting existing change-types into the context of the app change-type, ownership is dynamically …
> [change-types] reusability through composition

- schemas/aws/terraform-resource-2.yml
Adding SMS as an accepted protocol. Originally found by @TGPSKI in OSD-14571
> [OSD-14637] allow sms protocol for aws sns terraform

- graphql-schemas/schema.yml
- schemas/app-sre/integration-1.yml
the selective dry-run feature implemented as part of https://issues.redhat.com/browse/APPSRE-6785 will benefit greatly from an activation/deactivation flag per integration. in case of an issue/bug, selective dry-runs can be disabled. defaults to `false`
Example:
```yaml
$schema: /app-sre/integration-1.yml
name: terraform-resources
pr_check:
...
check_only_affected_shards: true
```
> integration pr-check flag to check only affected shards on dry-runs

- graphql-schemas/schema.yml
- schemas/dependencies/quay-org-1.yml
The schema mimics how we include/exclude tags when we mirror containers.
part of APPSRE-6916
> Add support to filter repos when mirroring orgs

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
this can be used for multiple purposes, such as audit, self-service, automation, and more.
> indicate an rds instance is used as a grafana datasource

- graphql-schemas/schema.yml
- schemas/dependencies/glitchtip-instance-1.yml
Refactor `glitchtip-instance-1` and get the automation user email address from a vault secret instead of specifying it manually. The vault secret is used by the glitchtip application during the startup to create/reconcile the API users.
This avoids glitchtip instance misconfigurations.
Ticket: [APPSRE-6904](https://issues.redhat.com/browse/APPSRE-6904)
> [glitchtip] get automation user email from vault secret

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
Add option to configure ip_address_type for ALB resources
part of https://issues.redhat.com/browse/APPSRE-7044
> terraform allow setting ip_address_type to ipv4/dualstack for alb

- graphql-schemas/schema.yml
- schemas/app-sre/integration-spec-1.yml
- schemas/cloudflare/dns-record-1.yml
- schemas/cloudflare/dns-zone-1.yml
- schemas/cloudflare/terraform-resource-1.yml
- schemas/common-1.json
* New schema for Cloudflare DNS zones
* Extract Cloudflare DNS record schema from terraform-resource-1
* New sharding strategy: per-cloudflare-zone
Be able to create and manage DNS zones in Cloudflare, then eventually migrate resource from Dyn since its DNS service will soon to be not supported.
Locally ran terraform-cloudflare-dns with new schemas was able to create records and zones based on dev-data 
Following query resulted in expected response:
```
{
zones: cloudflare_dns_zone_v1 {
zone
account {
name
description
providerVersion
apiCredentials {
path
field
format
version
}
terraformStateAccount {
name
consoleUrl
terraformUsername
automationToken {
path
field
}
}
}
records {
identifier
name
type
ttl
value
priority
data {
algorithm
protocol
public_key
digest_type
digest
key_tag
flags
} …
```
> Support Cloudflare DNS Zones

- graphql-schemas/schema.yml
- schemas/app-sre/integration-spec-1.yml
- schemas/cloudflare/dns-record-1.yml
- schemas/cloudflare/dns-zone-1.yml
- schemas/cloudflare/terraform-resource-1.yml
- schemas/common-1.json
Be able to create and manage DNS zones in Cloudflare, then eventually migrate resource from Dyn since its DNS service will soon to be not supported.
- Support Cloudflare DNS Zones;
- Add new sharding strategy: per-cloudflare-zone; 
- Add identifier to dns-record-1;
- Use a common Cloudflare DNS record schema between external resource and standalone Cloudflare zone.
Running terraform-cloudflare-dns and terraform-cloudflare-resources locally.
Following query resulted in expected response:
```
{
zones: cloudflare_dns_zone_v1 {
zone
account {
name
description
providerVersion
apiCredentials {
path
field
format
version
}
terraformStateAccount {
name
consoleUrl
terraformUsername
automationToken {
path
field
}
}
}
records {
identifier
name
type
ttl
value
priority
data {
algorithm
protocol …
```
> Support Standalone Cloudflare DNS Zones

- graphql-schemas/schema.yml
- schemas/vault-config/instance-auth-1.yml
APPSRE-7074
This will be utilized by vault-manager to determine if kube auth should be utilized instead of an approle/token. This is in the form of an optional attribute instead of a separate auth option because vault-manager will still rely on approle/token within pr checks and for local execution.
> add optional kube role name to vault instance auth

- graphql-schemas/schema.yml
- schemas/app-sre/app-1.yml
this has not been in use for a long time now, since the removal of the `gitlab-integrations` integration.
> remove jira ref from code components

- graphql-schemas/schema.yml
- schemas/app-sre/app-1.yml
Reverts app-sre/qontract-schemas#396
This is still being used in `gitlab-projects` and `gitlab-labeler` integrations.
> Revert "remove jira ref from code components"

- schemas/openshift/cluster-1.yml
The `glitchtip-project-dsn` integration can be disabled per cluster
> glitchtip-project-dsn cluster.disable property

- schemas/aws/asg-defaults-1.yml
This new strategy strikes a balance between cost and interruption risk.
The `spot_instance_pools` parameter is only available with the
`lowest-price` strategy, so it needs to be set to 0 for other
strategies.
https://aws.amazon.com/blogs/compute/introducing-price-capacity-optimized-allocation-strategy-for-ec2-spot-instances/
> aws/asg-defaults-1: add support for `price-capacity-optimized`

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
SA tokens usually have no org id associated with them but we rely on `ocm whoami` to find the org id to use when filtering for clusters. when we move forward with SAs that don't have an org association, we need another way to identify the org of an `/openshift/openshift-cluster-manager-1.yml`.
this schema changes makes the org association of an `/openshift/openshift-cluster-manager-1.yml` explicit by adding an `orgId` property to it.
attention: this is a mandatory new property, so a breaking schema change
https://issues.redhat.com/browse/APPSRE-7252
> [ocm] add mandatory orgId field

- graphql-schemas/schema.yml
This fixes a validation error in app-interface use of shardSpecOverrride, for details see the build of this MR:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/52065
> Make awsAccounts a list

- schemas/cloudflare/dns-zone-1.yml
Increase the number of record to 1500 to accommodate a large zone from Dyn
> Increase the number of record in a Cloudflare DNS zone to 1500

- graphql-schemas/schema.yml
- schemas/access/user-1.yml
This is part of [APPSRE-6367](https://issues.redhat.com/browse/APPSRE-6367):
```
AC:
enhance ldap-users to remove references to a deleted user file from aws account reset password sections.
```
The schema for user lookups was extended to include AWS account `resetPasswords`.  This allows the files containing the user to be included in a user lookup query:
```
aws_accounts {
path
}
```
Testing was performed locally with qontract-reconcile-cli and qd.
> updating schemas to include lookups for password resets APPSRE-6367

- schemas/cloudflare/dns-record-1.yml
Tested by locally adding AAAA record and seeing it in the query.
> Supporting AAAA record.

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
- schemas/openshift/openshift-cluster-manager-environment-1.yml
add a schema `/openshift/openshift-cluster-manager-environment-1.yml` which represents an actual instance of OCM like stage, integration or prod.
the current `/openshift/openshift-cluster-manager-1.yml` schema represents an OCM organization and not a instance of OCM. since we are adding more and more OCM organizations, this will lead to repeating metadata like URLs and credentials.
certain integrations will also start revolving around OCM instances and not organizations so having all of them as referenceable resources is a good next schema evolution.
All OCM environments will be referenced by a datafile like this ...
```yaml
$schema: /openshift/openshift-cluster-manager-environment-1.yml
name: ocm-production
description: OpenShift Cluster Manager Production Environment
url: …
```
> [ocm] introduce schema to for an OCM environment

- schemas/common-1.json
- schemas/openshift/openshift-resource-vault-secret-1.yml
To avoid `Replacing double-slashes ("//") in path with single slash ("/") to avoid Vault redirect response.` openshift-vault-secret warnings, enforce vault secret path without leading or ending /
Ticket: [APPSRE-7398](https://issues.redhat.com/browse/APPSRE-7398)
> vault secret path must not start or end with a /

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
Also adds support for the fixed-response action type
The refactoring was needed as previously the `forward` action was implied as that was the only one we supported. Now the schema supports additional action types and better aligns with the corresponding [terraform resource arguments](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#action-blocks)
Before
```yaml
rules:
- condition:
path: /v2/foo/*
action:
- target: main-target
weight: 100
- target: other-target
weight: 0
```
After
```yaml
rules:
- condition:
path: /v2/foo/*
action:
type: forward
forward:
target_group:
- target: main-target
weight: 100
- target: other-target
weight: 0
- condition:
path: /v2/*
action:
type: fixed-response
fixed_response:
content_type: text/plain
message_body: YOU …
```
> Refactor AWS ALB action to support multiple action types

- graphql-schemas/schema.yml
- schemas/openshift/openshift-resource-1.yml
Tests have been added as a array of strings as qontract-server doesn't like them to be resources that can be resolved. That works for a single resource, not for an array of resources.
Part of APPSRE-7018
> Change schema to support prom tester filtering

- schemas/openshift/prometheus-rule-1.yml
This is part of APPSRE-7018 as we're correctly marking all Prometheus rules without schema annotation.
> Add more valid values for prometheus rules labels

- schemas/openshift/cluster-1.yml
In https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/65388, I was getting the following when I worked with a file without `auth`:
```
reconcile.utils.gql.GqlApiError: `error` returned with GraphQL response
{
"message": "Cannot return null for non-nullable field Cluster_v1.auth.",
"locations": [
{
"line": 25,
"column": 5
}
],
"path": [
"clusters",
40,
"auth"
],
"extensions": {
"code": "INTERNAL_SERVER_ERROR"
}
}
```
> openshift/cluster-1.yml: make `auth` required

- schemas/dependencies/jenkins-config-1.yml
`app` field should be required in `jenkins-config-1`, it's `isRequired: true` in https://github.com/app-sre/qontract-schemas/blob/5a6d56f2db197b20d36b72ccf004204a13d9d6bd/graphql-schemas/schema.yml#L482
> Add app to required in jenkins-config-1

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-2.yml
with such a flag set to `true`, we can put more trust in a saas file owner and grant them wider permissions, such as full management over `targets`.
> add validate targets in app attribute to saas file

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
part of https://issues.redhat.com/browse/APPSRE-7652
enables using assume role similar to other network connectivity definitions.
> add support to assume role in account-vpc-mesh

- schemas/openshift/prometheus-rule-1.yml
We (RHOBS) team are in the process of migrating our SLO rules to Pyrra, as app-interface also plans to migrate to it. It is a tool which helps generate multi-burn rate alerts in Prometheus format, when a availability or latency SLO is specified
We are now in the process of deploying our new SLO alerts to stage (see stage MR with full details: [!67722](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/67722))
We would like to add three labels (`slo`, `short_burnrate_window` and `long_burnrate_window`) to the prometheus schema in order to better represent the alerts and which SLO they guard, and what burn rate window they represent (alert example with mentioned label [here](https://github.com/rhobs/configuration/blob/main/resources/observability/prometheusrules/rhobs-slos- …
> Add `slo`, `long_burnrate_window` & `short_burnrate_window` labels to Prometheus rule schema

- schemas/openshift/prometheus-rule-1.yml
This PR adds a `group` label to the Prometheus rule schema, as it is sometimes necessary to partition metrics according to API group, and query them in a rule.
> Add group label to Prometheus rule schema

- schemas/app-interface/prometheus-rule-test-1.yml
- schemas/app-sre/slo-document-1.yml
- schemas/openshift/prometheus-rule-1.yml
Prometheus allows having `expr` be set to an integer or a string. You can try this out, using the example rule file below and `promtool`,
```yaml
groups:
- interval: 30s
name: are-valid-rules
rules:
- alert: AlwaysFiringAlert
annotations:
description: Firing alert!
message: Alert fired.
expr: 1
for: 1m
labels:
severity: page
- record: AlwaysTwo
expr: 2
labels:
count: two
```
Promtool output,
```bash
$ promtool check rules rules.yaml
Checking rules.yaml
SUCCESS: 2 rules found
```
Prometheus-operator also follows the same convention, and this was explicitly done in https://github.com/prometheus-operator/prometheus-operator/pull/1845 (issue ref: https://github.com/prometheus-operator/prometheus-operator/issues/1831).
This PR ensures, that the schema aligns with upstream, and converts `expr` …
> Ensure Prometheus `expr` type is consistent with prometheus-operator

- schemas/aws/account-1.yml
- schemas/openshift/cluster-1.yml
Add the `aws-ami-cleanup` integration to the list of integrations allowed to be disabled on the account and cluster level.
Signed-off-by: Krzysztof Wilczyński <kwilczynski@redhat.com>
> Add aws-ami-cleanup to list of integrations allowed to be disabled

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
part of https://issues.redhat.com/browse/APPSRE-7734
this PR adds support to allow creating roles with:
- a different assume action (instead of AssumeRole)
- a Federated assume Principal
this is required to attach IAM roles to OpenShift ServiceAccounts.
this fits the backplane usage, but is a good pattern instead of using IAM credentials, so this possibly opens up a door for https://issues.redhat.com/browse/APPSRE-4201
> add support for assume action and Federated assume principal

- graphql-schemas/schema.yml
the use case is to validate that all apps are covered by self-service.
querying via the app is much simpler.
> add backref from app to role self-service

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
Part of the broader epic https://issues.redhat.com/browse/SDE-2887
https://issues.redhat.com/browse/APPSRE-7525
This PR adds support to set the data_classification field on RDS resource schema.
> Add data_classification to RDS schema

- schemas/app-interface/app-interface-settings-1.yml
We need to shorten the name due to how Tekton names PipelineRun retries, see APPSRE-6031 for details.
This property is actually only used by Visual Qontract and it should be removed as it only partially reflects the reality after openshift-tekton-resources.
> Allow for more names in the saas deploy template

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
The `users.name` attribute is used as an AWS resource identifier. Make this attribute an identifier in the schemas and limit it to 64 chars.
> [terraform-msk] make users name attribute an identifier

- graphql-schemas/schema.yml
- schemas/app-interface/change-type-1.yml
introduce a change-type context field `where: backrefs` to indicate that ownership expansion should be driven by resourcefile backrefs
```yaml
changes:
- provider: change-type
changeTypes:
- $ref: /app-interface/changetype/rds-defaults-maintainer.yaml
context:
where: backrefs (1)
selector: externalResources[?(@.provider=="aws")].resources[?(@.provider=="rds")].defaults (2)
```
(1) `where: backrefs` defines that the backrefs of a resourcefile need to be inspected in order to relate it back to the owned namespace file
(2) ... but to be more restrictive, the RDS resource file must be used in a very specific location within the namespace file
> [change-owners] resourcefile backrefs for ownership expansion

- schemas/aws/asg-defaults-1.yml
Adds the ability to specify vcpu, memory, and excluded instance types. While instance_requirements supports more parameters, expose just the ones needed for basic usage at first.
app-sre/qontract-reconcile#3595
> aws/asg-defaults: allow specifying instance_requirements

- graphql-schemas/schema.yml
part of https://issues.redhat.com/browse/APPSRE-4926
to be able to find escalation policies referencing jira boards (to get the jira component implemented in #477)
> add backref from jira board to escalation policy via channel

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
make the /app-sre/escalation-policy-1.yml schema eligible for self-service
for a datafile to be self-serviceable, it must be mentioned in the `self_service.datafiles` enum of `/access/role-1.yml` additionally, the GQL type must define the `datafile` property referencing the schema.
https://issues.redhat.com/browse/APPSRE-7955
> make the escalation-policy schema eligible for self-service

- graphql-schemas/schema.yml
- schemas/openshift/cluster-upgrade-policy-1.yml
implement version blocks per-cluster. this can be used to individually freeze/stop the upgrade process
part of https://issues.redhat.com/browse/APPSRE-7870
> [AUS] individual version blocks per upgrade policy / cluster

- graphql-schemas/schema.yml
- schemas/aws/cleanup-option-1.yml
Log groups are created with infinite log retention. All log groups should have a retention period of 3 months in order to keep storage costs in check. This change would create the following within an account file in app-interface:
```
---
$schema: /aws/account-1.yml
name: <aws-account-name>
cleanup:
- provider: cloudwatch
regex: '<some-log-path>'
retention_in_days: 90d
```
Note that this change is not affecting log groups managed by CLO.
Part of [APPSRE-7249](https://issues.redhat.com/browse/APPSRE-7249)
> Schema addition for log retention

- schemas/app-sre/saas-file-target-1.yml
https://issues.redhat.com/browse/RHCLOUD-27381
This should add support for `stable` as a valid branch name to deploy console.redhat.com Frontend applications from stable branches
> Add stable as a supported branch name for SaaS template

- graphql-schemas/schema.yml
- schemas/dependencies/dynatrace-environment-1.yml
- schemas/openshift/cluster-1.yml
- schemas/openshift/namespace-1.yml
This introduces the dynatrace environment as a dependency. That dependency can be used by clusters to specify where to send logs to. Additionally, namespaces have a flag to turn on/off dynatrace log ingestion.
Further, this schema can be easily extended to inhibit token information.
> APPSRE-8144 add dynatrace environment

- graphql-schemas/schema.yml
- schemas/dependencies/glitchtip-project-1.yml
Add an optional `glitchtip-project-1.projectId` attribute. 
In Glitchtip, a project is referenced by a `slug`; for convenience, the integration deviates this `slug` based on the `glitchtip-project-1.name` attribute. If a tenant wants to rename a project, the integration can't figure out the original `slug` anymore and will delete and recreate the project. To omit that, a tenant can manually specify the `slug` via `glitchtip-project-1.projectId ` to rename a project.
> [glitchtip-project-1.yml] add glitchtipId attribute

- graphql-schemas/schema.yml
- schemas/dependencies/jira-board-1.yml
This permits a team to specify a new issue type for jiralert to use.
See downstream: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/76908
Issue https://issues.redhat.com/browse/RHTAPSRE-129
> Add issueType to jira board schema

- schemas/aws/terraform-resource-2.yml
part of https://issues.redhat.com/browse/APPSRE-8143
an examples for a name that is valid and not covered by the existing schema: `OrganizationAccountAccessRole`
> update terraform resource schema to allow all valid IAM Role names

- schemas/app-sre/integration-1.yml
- schemas/openshift/lean-namespace-1.yml
- schemas/openshift/namespace-reference-1.yml
in some cases a lean definition of a namespace in a cluster with an automation token and some context (env) is all that is needed.
this is a proposal of such an implementation that works for integrations-manager with 0 code changes.
> introduce lean namespace

- graphql-schemas/schema.yml
- schemas/vault-config/role-1.yml
[APPSRE-8173](https://issues.redhat.com/browse/APPSRE-8173)
dependency for https://github.com/app-sre/vault-manager/pull/125
**Changes:**
Replace string type with applicable schema references for the following attributes in vault roles:
* `policies/token_policies`
* `mount`
The effect of these changes is improved readability and validation during pr check.
> Increase usage of file refs within vault role configs

- graphql-schemas/schema.yml
- schemas/openshift/deploy-resources-1.yml
- schemas/openshift/resource-limits-requirements-1.yml
- schemas/openshift/resource-requests-requirements-1.yml
As part of [APPSRE-8174](https://issues.redhat.com/browse/APPSRE-8174), we need to allow `limits.cpu` to be not set.
> Allow cpu limits to be optional

- graphql-schemas/schema.yml
- schemas/app-sre/gabi-instance-1.yml
Add support for the read replicas requirement waiver to GABI schema through a new optional string type attribute called `readReplicasWaiverPledge` that will be used to store a free-form waiver pledge text.
Related:
- [APPSRE-7135](https://issues.redhat.com/browse/APPSRE-7135)
- [!78208](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/78208)
Signed-off-by: Krzysztof Wilczyński <kwilczynski@redhat.com>
> APPSRE-7135: Add support for read replicas waiver to GABI schema

- graphql-schemas/schema.yml
- schemas/common-1.json
- schemas/dependencies/glitchtip-project-1.yml
- schemas/dependencies/glitchtip-project-alert-1.yml
Introduce additional schema to represent Glitchtip project alerts.
Example: https://gitlab.cee.redhat.com/app-sre/app-interface-dev-data/-/merge_requests/79
Ticket: [APPSRE-7521](https://issues.redhat.com/browse/APPSRE-7521)
Design-doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/glitchtip-project-alerts.md
> [glitchtip-project-alerts] attributes

- graphql-schemas/schema.yml
- schemas/dependencies/glitchtip-project-alert-1.yml
A webhook URL may contain credentials, e.g. slack webhooks. Add an `urlSecret` attribute to retrieve a URL via Vault as well.
Ticket: [[glitchtip project-alerts] Webhook URL from vault](https://issues.redhat.com/browse/APPSRE-8288)
> [glitchtip-project-alert] add urlSecret attribute

- schemas/common-1.json
the `__identifier` field is a field managed by qontract-validator when an object defines one or many `isContextUnique` fields. it holds a hash which is then used to figure out if an object is really unique within the context.
to enable the context uniqueness check also on lists of crossrefs, the crossref jsonschema type needs to declare it so that qontract-bundler can add it and qontract-validator can still validate the schema.
completements https://github.com/app-sre/qontract-validator/pull/58
part of https://issues.redhat.com/browse/APPSRE-8308
> __identifier field on crossrefs to enable validation of context uniqeness in lists of crossref objects

- schemas/aws/terraform-resource-2.yml
the s3 provider defines `replication_configurations` as a valid config option, but it also needs to be defined outside of the `oneOf` sections to be verifiable by jsonschema.
> add missing replication_configurations property

- graphql-schemas/schema.yml
- schemas/dependencies/jenkins-instance-1.yml
Field name returned in jenkins api response is `jvmOptions` [doc]( https://javadoc.jenkins.io/plugin/ssh-slaves/hudson/plugins/sshslaves/SSHConnector.html), update schema to use the same case to avoid reconcile loop by sharing model.
Follow up for https://github.com/app-sre/qontract-schemas/pull/524
> Fix jvmOptions field name case

- graphql-schemas/schema.yml
- schemas/dependencies/glitchtip-organization-1.yml
- schemas/dependencies/glitchtip-project-1.yml
- schemas/dependencies/glitchtip-team-1.yml
Refactor the glitchtip schemas to allow usage for SRE error tracking capability.
Ticket: [[SRE Capability] Error tracking](https://issues.redhat.com/browse/SDE-3254)
Design-doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/sre-capability-error-tracking.md
> [glitchtip] changes for error-tracking capability

- graphql-schemas/schema.yml
- schemas/dependencies/glitchtip-organization-1.yml
- schemas/dependencies/glitchtip-team-1.yml
To ease the glitchtip configuration, mark the `labels` attributes as non-required.
> [glitchtip] labels are not required

- graphql-schemas/schema.yml
- schemas/app-sre/integration-sharding-1.yml
sharding and shard-spec overrides for ocm-organizations allows us to spread the load, isolate error domains and test integration upgrades in selected organizations
```yaml
$schema: /app-sre/integration-1.yml
name: an-ocm-related-organization
managed:
- namespace:
$ref: /a-namespace.yml
...
sharding:
strategy: per-ocm-organization
shardSpecOverrides:
- shard:
$ref: /org-1.yml
imageRef: abcdefg
- shard:
$ref: /org-2.yml
disabled: true
```
part of https://issues.redhat.com/browse/APPSRE-8414
> allow ocm-organization sharding for integrations

- graphql-schemas/schema.yml
- schemas/aws/account-1.yml
- schemas/aws/cleanup-option-1.yml
`region` is to support cleanup in different region other than default one.
`delete_empty_log_group` is used to enable deletion of empty log groups.
Also allow `aws-cloudwatch-log-retention` to be disabled per account.
[APPSRE-8425](https://issues.redhat.com/browse/APPSRE-8425)
> Add region and delete_empty_log_group to cloudwatch cleanup option

- schemas/openshift/prometheus-rule-1.yml
This is a new label being added to the SLO rules created by Pyrra, which indicates the exhaustion time of the SLO.
Signed-off-by: Douglas Camata <159076+douglascamata@users.noreply.github.com>
> Add `exhaustion` label to prometheus rule schema

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
`nodes`, `instance_type` and `autoscale` are no long used after https://github.com/app-sre/qontract-reconcile/pull/3825.
Also set `machinePools` to have at least 1 item.
[APPSRE-8258](https://issues.redhat.com/browse/APPSRE-8258)
> Cleanup cluster schema for default machine pool handling

- graphql-schemas/schema.yml
- schemas/app-interface/app-interface-settings-1.yml
- schemas/dependencies/glitchtip-instance-1.yml
- schemas/dependencies/glitchtip-project-1.yml
- schemas/dependencies/jira-board-1.yml
Add two new jira related attributes to the `glitchtip-project` schema to support Jira ticket creation for Glitchtip alerts.
Set the `jenkins.name` type to an identifier because it's the Jira project key that doesn't allow spaces.
Ticket: https://issues.redhat.com/browse/APPSRE-8238
Design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/glitchtip-jira.md
> [glitchtip-project] introduce Jira attributes

- graphql-schemas/schema.yml
- schemas/aws/parameter-group-1.yml
- schemas/aws/terraform-resource-2.yml
To enable self-service on parameter groups, the parameter groups must have a schema.
This new `/aws/parameter-group-1.yml` schema supports MySQL, Postgres, and Redis (Elasticache).
Ticket: https://issues.redhat.com/browse/APPSRE-8310
> /aws/parameter-group-1.yml schema

- graphql-schemas/schema.yml
- schemas/app-sre/slo-document-1.yml
Currently the slo-document `.namespaces` contains a list of `namespace` objects linked to the app, where the SLOs in the slo document is applicable.
In addition to the `namespace` property, this MR introduces a new  `targetNamespace` property which will inform the SLO-Document alertmanager-to-status-board flow where to create the dynamic rules:
https://gitlab.cee.redhat.com/jmelisba/app-interface/-/blob/259c9c72635c3c7e4dbaf1905d327e756970e66c/resources/observability/prometheusrules/status-board-slo-generated-alerts.prometheusrules.yaml.j2
> add targetNamespace to slo-document

- graphql-schemas/schema.yml
- schemas/access/membership-provider-1.yml
- schemas/access/role-1.yml
We should be able to run integrations that rely on roles, users and role membership in the sre-capabilities repo with as little change as possible, while not being forced to manage a whole set of users and role memberships.
The central concept for grouping and permissions will still be `/access/role-1.yml` but membership will be pluggable. A configuration section memberSource can be used to bring in user and role membership information from different sources, defined via a schema `/access/membership-provider-1.yml`.
A membership provider can be any system that provides groups and users (provider pattern). User information needs to include some sort of username that can be mapped to org_username. This schema change introduces the memebership provider mechanism and offers app-interface as a …
> declare membership sources in a role

- graphql-schemas/schema.yml
- schemas/app-sre/slo-document-1.yml
`targetNamespace` is confusing, it has been renamed to `SLONamespace` and it now includes a description explaining its purpose.
> rename from targetNamespace to SLONamespace

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
Right now a-i is the source of truth for external configuration labels on clusters. We use them to mark hive shards and backplane shards. But it seems that other parties also put labels on clusters, e.g. cluster service adds "legacy-ingress-support" when a cluster gets upgraded to 4.14. our current integrations are deleting such labels because they are not listed in cluster files.
This PR introduces an allow list for labels in an OCM organizations. clusters of that organization can only manage labels from that list and will ignore all others.
https://issues.redhat.com/browse/APPSRE-8521
> allowlist for OCM cluster external config labels

- graphql-schemas/schema.yml
- schemas/dependencies/glitchtip-project-1.yml
Add a `jira.labels` field to `glitchtip-project-1` to support custom labels on create Jira alert tickets.
Ticket: [APPSRE-8523](https://issues.redhat.com/browse/APPSRE-8523)
> [glitchtip-project-alerts] support custom jira labels

- graphql-schemas/schema.yml
- schemas/aws/terraform-repo-1.yml
[APPSRE-8520](https://issues.redhat.com/browse/APPSRE-8520)
Allows a user to specify that a Terraform Repo needs additional validation to use [AWS FIPS endpoints](https://aws.amazon.com/compliance/fips/). This will come with a QR change to handle the updated schema as well as a validation step that occurs in the Terraform Repo executor.
Corresponds with the following PRs:
- QR: https://github.com/app-sre/qontract-reconcile/pull/3938
- Executor: https://github.com/app-sre/terraform-repo-executor/pull/16
> FIPS Validation for Terraform Repos

- schemas/openshift/cluster-1.yml
ROSA HCP `min_replicas` allow 1 for multiple availability zone clusters, each availability zone has it's own pool, so 3 zone will have 3 pools, each pool can have 1 node.
[doc](https://docs.openshift.com/rosa/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-instance-types_rosa-service-definition)
> Update machine pool min_replicas minimum to 1

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
adds a field to hold the OIDC provider endpoint URL of a cluster. this field will be updated automatically by an integration, similar to `id` and `external_id` and is useful when defining IAM roles and trust policies for STS
part of https://issues.redhat.com/browse/APPSRE-8656
> cluster OIDC provider endpoint URL

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
many moons ago, we used to have a per-cluster EFK stack.
> make cluster.kibanaUrl optional

- .gitignore
- graphql-schemas/schema.yml
- schemas/dependencies/dynatrace-environment-1.yml
OSDFM need to be able to generate configmap about the mapping of DT regions and HCP AWS regions.
I have run qontract server with this branch locally.
> Adding region and environment information for Dynatrace environments.

- graphql-schemas/schema.yml
- schemas/dependencies/jira-board-1.yml
Add `disable.integrations` to jira-board to support disabling integrations in case of board errors.
Ticket: [APPSRE-8620](https://issues.redhat.com/browse/APPSRE-8620)
> [jira-board] disable.integrations support

- graphql-schemas/schema.yml
- schemas/cloudflare/terraform-resource-1.yml
This adds a new kind of resources to cloudflare terraform resources schema.
Related to:
https://issues.redhat.com/browse/APPSRE-8315
It it backwards compatible. It was tested by adding the following object to `externalResources.[provider["cloudflare"]][provider["zone"]]` in `data/services/quayio/namespaces/quays02ue1.yml` in `app-interface`.
```yaml
custom_ssl_certificates:
- identifier: quayio-stage-custom-ssl
type: legacy_custom
bundle_method: ubiquitous
geo_restriction: "us"
certificate_secret:
certificate:
path: some/path
field: cert.csr
version: 1
key:
path: some/other/path
field: cert.key
version: 1
```
> Add cloudflare custom ssl certificates to cloudflare terraform resources

- schemas/app-sre/app-1.yml
With codeComponents URL ending with `/` our backup service throw errors like in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/89905
```
6:31:16 remote: Not Found
06:31:16 fatal: repository 'https://github.com/redhat-appstudio/service-provider-integration-operator/.git/' not found
```
So it's better to catch such errors in PR-check
> APPSRE-8667: disallow end slash in git repo URLs

- schemas/access/role-1.yml
Would like to enable our `bot-owner` changetype, but its missing from the schema.
> make bots self-servicable

- graphql-schemas/schema.yml
- schemas/dependencies/dynatrace-environment-1.yml
We need to accommodate for 2 token:
- the bootstrapAPIToken is used to generate new API tokens for HS
- the automationAPIToken is used by app-interface automations to interact with dynatrace API
Note, that none of the tokens is required. I.e., a dynatrace environment is not necessarily tied to a HS region and/or app-interface automation.
Further, we remove the region enum, as onboarding a new region requires a change to the schema which is not self-servicable.
> APPSRE-8660 adjust schema for more self-service

- graphql-schemas/schema.yml
- schemas/app-sre/integration-1.yml
Add `run_order` to `pr_check` section for integration, so some integrations can be grouped to run before others.
[APPSRE-8759](https://issues.redhat.com/browse/APPSRE-8759)
> Add run_order to integration pr_check

- graphql-schemas/schema.yml
- schemas/common-1.json
- schemas/dependencies/glitchtip-project-1.yml
Replace unused `glitchtip-project.acceptEvents` with `glitchtip-project.eventThrottleRate` to throttle Glitchtip event ingests.
Ticket: [APPSRE-9732](https://issues.redhat.com/browse/APPSRE-9732)
> [glitchtip] eventThrottleRate attribute

- graphql-schemas/schema.yml
- schemas/dependencies/dynatrace-environment-1.yml
The ID is easier to consume than the URL for most cases.
> APPSRE-9780 dynatrace environmentID

- schemas/aws/terraform-resource-2.yml
Adding all current general purpose RDS instances + all Graviton based memory optimized instances
PS: I moved `db.m3.medium` lower in the list to keep types together.
> AWS RDS instances refresh

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
add an option to control if traffic via a TGW attachment should be able to reach the API server of a private HCP
part of https://issues.redhat.com/browse/APPSRE-9883
prereq for https://github.com/app-sre/qontract-reconcile/pull/4152
> [terraform-tgw-attachments] control traffic to private HCP API

- graphql-schemas/schema.yml
this will enable self-service for instances in a gabi instance file approved by the namespace (app) owners.
> add backref from namespace to gabi instances

- graphql-schemas/schema.yml
- schemas/dependencies/prometheus-instance-1.yml
- schemas/openshift/openshift-cluster-manager-1.yml
- schemas/openshift/openshift-cluster-manager-environment-1.yml
this way cluster health information can be queried for a fleet of clusters under an environment
Define a prometheus instance representing telemeter...
```yaml
---
$schema: /dependencies/prometheus-instance-1.yml
name: telemeter
baseUrl: https://infogw-proxy.api.openshift.com
queryPath: /api/v1/query
auth:
provider: bearer
token:
field: token
path: path/to/vault/secret
```
... and link it to an OCM environment
```yaml
---
$schema: /openshift/openshift-cluster-manager-environment-1.yml
name: ocm-production
url: https://api.openshift.com
...
telemeter:
$ref: /dependencies/prometheus/telemeter-production.yaml
```
part of https://issues.redhat.com/browse/APPSRE-8789
> define a telemeter instance for an OCM environment

- schemas/aws/policy-1.yml
- schemas/common-1.json
Limit the policy name length to 128.
See [IAM quotas](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html) for more details
> aws-policy: limit policy name to max 128 chars

- schemas/openshift/cluster-upgrade-policy-1.yml
add the `gate-ingress` version gate to the list of valid gates to be auto acknowledable by the AUS version-gate-approver
part of https://issues.redhat.com/browse/APPSRE-7949
> [AUS] enable ingress gate to be auto approvable

- schemas/common-1.json
- schemas/json-schema-spec-draft-06.json
- schemas/metaschema-1.json
Store json-schema-spec draft-06 in this repository to avoid being unable to validate if json-schema.org is down.
Copied from https://raw.githubusercontent.com/json-schema-org/json-schema-spec/draft-06/schema.json
and make sure it is used by the common schemas.
Renamed $ref and $id to avoid qontract-validator reaching the json-schema.org website to fetch it
[APPSRE-9951](https://issues.redhat.com/browse/APPSRE-9951)
> Store json schema spec draft 06 in the repository

- schemas/app-sre/saas-file-target-1.yml
the schema needs to be updated to allow branches following the new
branch strategy that OCP follows (release-*). This was discussed before
in #120 but decided against. With the new progressive delivery strategy,
this will need to be allowed.
Signed-off-by: Brady Pratt <bpratt@redhat.com>
> SDCICD-1254: allow release-* branch names

- graphql-schemas/schema.yml
- schemas/aws/vpc-request-1.yml
Name is good in app-interface universe but for a Terraform resource identifier has better restrictions. The same identifier can serve as a `Name` tag.
> Fix change VPC request name to identifier

- graphql-schemas/schema.yml
- schemas/app-sre/escalation-policy-1.yml
to be able to use for labeling jira tickets created by our automation.
for example, with jiralert: https://github.com/prometheus-community/jiralert/blob/d43cbab62126d543e8e789f6374d9e745693cce2/examples/jiralert.yml#L27
> add jira labels to escalation policy

- graphql-schemas/schema.yml
- schemas/acs/acs-policy-1.yml
part of https://issues.redhat.com/browse/APPSRE-10043
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/102231
As `notifiers` is a single form of an integration, we will add a new field to the schema: `integrations`. This object will include a new `notifiers` section, which will have a field for each notifier integration we want to implement, starting with `jira`.
The `integrations.notifiers.jira` field will include `escalationPolicy`, a reference to an Escalation Policy, which will be used to collect the required information to manage Notifiers. Specifically, the first Jira board referenced under `channels` will be used to define the default project, Severity to Priority mappings, and more.
> acs policy introduce integrations

- graphql-schemas/schema.yml
- schemas/aws/vpc-request-1.yml
I've noticed that when we create a subnet we generally provide an availability zone, so I'm adding this to the vpc-request schema.
> Add availability zone to vpc request subnets

- schemas/app-sre/saas-file-2.yml
- schemas/app-sre/saas-file-authentication-1.yml
by extracting the schema to its own object, and adding a `oneOf` validation such that authentication is either inlined in the saas file or referenced in a different file.
wondering if this is working? here is a live example: https://github.com/app-sre/qontract-schemas/blob/973b61443fe6923d6f24288237252cba5a219ca4/schemas/app-sre/saas-file-2.yml#L113-L118
> enable saas file authentication to be inlined or referenced

- graphql-schemas/schema.yml
- schemas/acs/acs-policy-1.yml
part of https://issues.redhat.com/browse/APPSRE-10043
design document: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/102231
following https://github.com/app-sre/qontract-reconcile/pull/4275, the root level `notifiers` field is deprecated in favor of `integrations.notifiers`.
> deprecate acs policy notifiers

- graphql-schemas/schema.yml
- schemas/aws/terraform-repo-1.yml
[APPSRE-8705](https://issues.redhat.com/browse/APPSRE-8705)
Implements new functionality for Terraform Repo based off of the [Milestone 1 design document](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/initiatives/terraform-repo-commercial.md?ref_type=heads#milestone-1-commercialize-terraform-repo). 
This adds two fields to a Terraform Repo representation in App Interface. The first of which allows a user to specify which version of the Terraform binary to use when planning/applying. The second allows them to load Vault secrets from a specified path as [Input Variables](https://developer.hashicorp.com/terraform/language/values/variables) and write any outputs from their Terraform apply to Vault using …
> [tf-repo schemas] Versioning and Vault Secrets

- graphql-schemas/schema.yml
- schemas/aws/vpc-request-1.yml
To be able to use azs the same way we use in the [Terraform VPC Module](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest) I've moved them to their own list.
> ♻️ Move availability zones to its own list

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
The goal is to enable our LDAP groups to be authZ groups for Bitwarden collections. Rover group requirements are:
* Rover group notes must contain the string `@BW@` somewhere
* At least 2 owners are set
This PR adds `notes` and `membersAreOwners` (both optional) to the `role.ldapGroup` attribute. `notes` will be Rover group notes, and `membersAreOwners: true` will also grant the `owners` permission to all group members.
Tickets
* [APPSRE-10201](https://issues.redhat.com/browse/APPSRE-10201)
* [APPSRE-8399](https://issues.redhat.com/browse/APPSRE-8399)
> :recycle: /access/role-1.yml: refactor ldapGroup attribute

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-target-1.yml
the idea would be to store version history continuously and only promote once soakDays passed
this concept is similar to the one of AUS, and may bring a standard to our different promotion processes.
> add soakDays for saas promotions

- graphql-schemas/schema.yml
- schemas/app-sre/maintenance-1.yml
- schemas/dependencies/status-provider-1.yml
the new schema `/app-sre/maintenance-1.yml` tracks details for maintenances, their time windows and announcements.
```yaml
$schema: /app-sre/maintenance-1.yml
name: maintenance name
title: Maintenance for xxx
stage: scheduled | in_progress | verifying | completed
affectedServices:
- $ref: to service
scheduledStart: ISO timestamp
scheduledEnd: ISO timestamp
announcements:
- provider: statuspage
announceAt: ISO timestamp
message: a message describing the maintenance on the status page
statuspage:
remindSubscribers: true | false
notifySubscribersOnStart: true | false
notifySubscribersOnCompletion: true | false
```
`/dependencies/status-page-component-1.yml` can participate in a maintenance by referencing it in their `/dependencies/status-provider-1.yml` section  and have their status managed …
> schema for service maintenances

- graphql-schemas/schema.yml
- schemas/access/role-1.yml
- schemas/app-sre/maintenance-1.yml
part of https://issues.redhat.com/browse/APPSRE-10224
adding a page reference to a maintenance for statuspage provider. also adding self-service for the schema.
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/maintenances.md
> statuspage-maintenances add more fields/features

- graphql-schemas/schema.yml
- schemas/openshift/cluster-1.yml
Enable openshift cost report at cluster level, so clusters can opt in or out for cost report.
[APPSRE-10104](https://issues.redhat.com/browse/APPSRE-10104)
> Add enable cost report flag to cluster

- schemas/dependencies/slack-workspace-1.yml
this is quite annoying, honestly
> remove integrations enum from slack workspace

- graphql-schemas/schema.yml
- schemas/dependencies/jira-board-1.yml
to enable per-board definition to override default jiralert definitions
> enable wontFixResolution and reopenDuration for a jira board

- schemas/aws/rds-defaults-1.yml
- schemas/aws/terraform-resource-2.yml
This is needed to fully support gp3
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#storage_throughput
> Add storage throughput to rds related schemas

- graphql-schemas/schema.yml
- schemas/aws/vpc-request-1.yml
To make it easier to remove VPCs in `app-interface` we are going to use the `delete: true` pattern.
That is necessaire because if all `vpc-request` from an account are removed the integration will skip the run and not remove the VPCs in the Terraform plan/apply stept
> Add delete flag to vpc-request

- graphql-schemas/schema.yml
- schemas/dependencies/glitchtip-project-1.yml
Use `escalationPolicy` instead of own jira board definition in `glitchtip-project-alert-1`. This enables jira components support for glitchtip jira tickets.
Ticket: [APPSRE-10356](https://issues.redhat.com/browse/APPSRE-10356)
> :recycle: glitchtip-project: replace jira board reference with escalation policy

- graphql-schemas/schema.yml
- schemas/aws/account-request-1.yml
Add `uid` to `/aws/account-request-1.yml`. If `uid` is specified, `aws-account-manager` will take over an existing account instead of creating a new one.
Ticket: [APPSRE-10430](https://issues.redhat.com/browse/APPSRE-10430)
> :sparkles: account-request: add UID attribute to support takeover of existing accounts

- graphql-schemas/schema.yml
- schemas/access/permission-1.yml
it would make sense for every usergroup to define in what channels they should be contacted. specifying channels should be at least mandatory to begin with.
> make slack permission channels mandatory

- graphql-schemas/schema.yml
- schemas/aws/account-request-1.yml
Add `additionalFeatures` attribute to `account-requests`. With the help of this attribute, we can control which templates must be rendered for a new account. E.g. 
```
$schema: /aws/account-request-1.yml
...
additionalFeatures:
rosa: false
aws_resource_exporter:
rds: true
```
will disable rosa quota limits and enable AWS resource exporter with RDS metrics.
Ticket: https://issues.redhat.com/browse/APPSRE-10384
> :sparkles: account-request: add additionalFeatures attribute

- graphql-schemas/schema.yml
- schemas/app-interface/template-1.yml
Make the jinja [whitespace control](https://jinja.palletsprojects.com/en/3.1.x/templates/#whitespace-control) behavior configurable for a template by introducing `trim_blocks`, `lstrip_blocks`, and `keep_trailing_newline` as `templateRenderOptions`. The default will still be `False` for all three options.
> :sparkles: templates: add templateRenderOptions attribute

- graphql-schemas/schema.yml
- schemas/aws/account-1.yml
part of https://issues.redhat.com/browse/APPSRE-10457
to be able to use a specified aws account as the billing account in a ROSA HCP cluster provisioning flow
> add aws billing account to aws account

- schemas/app-sre/saas-file-2.yml
To support ActiveGate images coming from each Dynatrace tenant, we'd like to allow pulling directly from there. 
Context: [APPSRE-10517](https://issues.redhat.com/browse/APPSRE-10517)
> Allow pulling image from Dynatrace registry.

- schemas/openshift/terraform-output-format-1.yml
dashes are allowed according to https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/#create-the-config-file
> allow dash in output format data keys

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
same functionality intended as for aws-iam-service-account
to be able to associate managed policies to a role.
> aws-iam-role support managed policies

- graphql-schemas/schema.yml
The `app.endPoints[].name` must be context-unique to be identifiable for automated updates. 
Ticket: [APPSRE-3989](https://issues.redhat.com/browse/APPSRE-3989)
>  endPoints: endpoint name must be context unique

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-2.yml
Cleaning up tech debt. We currently use `publishJobLogs` flag in saas files to identify whether a saas file holds test jobs. This also has effects on whether target_config_hash is used. However, this is very hidden knowledge and caused confusion in the past.
This PR introduces the flag `hasTestJobs` for saas files, which explicitly states whether tests are part of this saas file. This flag will then be used by integrations (e.g., saasherder, SAPM).
> APPSRE-7516 flag for saas files holding tests

- Makefile
> preparation to ping author on MR

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-2.yml
This reverts commit 5db9e797fa44c122ebd8910d8a9e237a66ee7704.
After discussion with @hemslo we decided to refine this a little. This feature is not used yet so it is safe to remove from schema.
I will open a follow up PR
> Revert "APPSRE-7516 flag for saas files holding tests (#700)"

- schemas/app-sre/saas-file-2.yml
`registry.connect.redhat.com` hosts a lot of useful images.  This updates the regular expression used to validate allowed image registries by adding support for `registry.connect.redhat.com`. This change ensures that images from this registry are correctly identified and allowed by our validation logic.
> extend the imagePattern regex to include registry.connect.redhat.com

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-target-1.yml
Explicit flag to declare whether a target should be re-deployed if there was a config change in the publisher. Previously, this was defined saas file wide via `publishJobLogs` flags.
Follow-up on https://github.com/app-sre/qontract-schemas/pull/700
cc @hemslo 
If desired, we can also have this flag on saas file level instead (i.e., enable/disable for all targets in a saas file).
> APPSRE-7516 redeploy on config change

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-2.yml
Due to saas progressive delivery efforts, it is likely that saas file names are more and more used in visualizations. That probably leads to more ppl trying to rename saas files. However, renaming saas files is hard and essentially means migrating targets from one saas to another (including auto promotions being stuck in current ref ...).
We introduce extra field display_name that can be used by visualizations (like backstage and our own grafana dashboard). I.e., we can keep `name` stable as currently we use it like an id.
Note, that `displayName` is required, so any external tooling can be sure it is available. We can add a simple migration script in app-interface to add this to all saas files.
> APPSRE-10767 displayName for saas file

- graphql-schemas/schema.yml
- schemas/aws/msk-defaults-1.yml
- schemas/aws/terraform-resource-2.yml
Add external resources version 2 (ERv2) related attributes to the `terraform-resources` MSK  provider.
Ticket: [APPSRE-10598](https://issues.redhat.com/browse/APPSRE-10598)
> :sparkles: terraform-resources: MSK ERv2 support

- schemas/openshift/cluster-1.yml
We need to label our cluster subscriptions accordingly for Dynatrace Token Provider (DTP). By doing so, DTP will provision proper dynatrace tokens for our clusters.
We are adding the `token-spec` field which defines what token spec DTP should use.
> APPSRE-10844 DTP token-spec label

- schemas/aws/account-1.yml
part of https://issues.redhat.com/browse/APPSRE-10862
this PR will forbid reset password unless `sso` is set to false.
> aws account resetPassword depends on sso being false

- graphql-schemas/schema.yml
- schemas/app-sre/slo-document-1.yml
https://issues.redhat.com/browse/APPSRE-8513
Allows unauthenticated local token-refresher svc access, much like what grafana does.
Something like
```yaml
$schema: /app-sre/slo-document-1.yml
name: rosa-classic-fleet-wide
namespaces:
- namespace:
$ref: /services/rosa-fleet-wide/classic/namespaces/rosa-fleet-wide.yml
prometheusAccess:
url: http://osd-token-refresher-prod.app-sre-observability-production.svc.cluster.local
SLONamespace:
$ref: /services/rhobs/observatorium-mst/namespaces/telemeter-prod-01/observatorium-mst-production.yml
```
> SLOD doc: set prometheusAccess creds as optional

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
[APPSRE-10769]https://issues.redhat.com/browse/APPSRE-10769
Adding all default values to ssl_policy.
Source: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/describe-ssl-policies.html#fs-supported-policies
I put it along side with the [aws_lb_listener](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener) values.
> Add ssl_policy alb resource schema

- graphql-schemas/schema.yml
- schemas/aws/elasticache-defaults-1.yml
- schemas/aws/parameter-group-1.yml
- schemas/aws/terraform-resource-2.yml
This PR introduces an `/aws/elasticache-defaults-1.yml` schema and adds all required ERv2 attributes to terraform-resources Elasticache definition.
A proper `/aws/elasticache-defaults-1.yml` schema allows tenant self-service, better documentation, and more straightforward ERv2 module code.
Ticket: [APPSRE-11001](https://issues.redhat.com/browse/APPSRE-11001)
> :sparkles: Elasticache ERv2 support and defaults schema

- graphql-schemas/schema.yml
- schemas/external-resources/module-1.yml
- schemas/external-resources/module-overrides-1.yml
- schemas/external-resources/settings-1.yml
Remove hardcoded `er-outputs-secrets` image and version.
The image and the version must be configured in `/external-resources/settings-1.yml` but can be overridden in `/external-resources/module-1.yml` and `/external-resources/module-overrides-1.yml`
Ticket: [APPSRE-11049](https://issues.redhat.com/browse/APPSRE-11049)
> :sparkles: ERv2: make outputs-secret image and version configurable

- graphql-schemas/schema.yml
- schemas/app-interface/app-interface-settings-1.yml
Adding both deprecated and new schema is necessary because some integrations rely on the production bundle to work. `integrations_manager` also queries app-interface settings to roll out a new version. 
The deprecated object will be removed after QR is deployed.
Related: https://github.com/app-sre/qontract-reconcile/pull/4748
> Improve terraform-resources provider exclusions

- schemas/aws/terraform-repo-1.yml
Allow users to specify newer versions of Terraform in their tf-repo spec file.
[APPSRE-11103](https://issues.redhat.com/browse/APPSRE-11103)
> [tf-repo] Allow for newer versions of TF binary

- schemas/openshift/cluster-1.yml
This pull request includes updates to the `schemas/openshift/cluster-1.yml` file to enhance the documentation of the schema properties. The most important changes include adding descriptions to the `private` and `internal` properties to clarify their usage and requirements.
Documentation updates:
* [`schemas/openshift/cluster-1.yml`](diffhunk://#diff-a09b65a72bf4f7457cb806d201e443ec6694862d5769e9066d32db0feb43fbc5R178): Added a description to the `private` property to specify that the kube API (load balancer) and router are private, and access requires peering.
* [`schemas/openshift/cluster-1.yml`](diffhunk://#diff-a09b65a72bf4f7457cb806d201e443ec6694862d5769e9066d32db0feb43fbc5R550): Added a description to the `internal` property to explain that the cluster is attached to the transit …
> docs(cluster): doc private and internal field description

- schemas/openshift/cluster-1.yml
During cluster creation, `jumpHost` is added to cluster file creation template for private non internal clusters, `automationToken` is added later by `openshift-cluster-bot` integration. Remove this dependency to avoid validation error `'automationToken' is a dependency of 'jumpHost'`.
> fix(jumpHost): remove dependencies on automationToken

- graphql-schemas/schema.yml
- schemas/aws/terraform-repo-1.yml
[APPSRE-11333](https://issues.redhat.com/browse/APPSRE-11333)
Allow our tenants using secrets for inputs/outputs to have the flexibility to specify one or the other, or both. Basically a [logical "disjunction"](https://en.wikipedia.org/wiki/Logical_disjunction)
Dependent MR:
- [Qontract Reconcile](https://github.com/app-sre/qontract-reconcile/pull/4799)
> [tf-repo secrets] update schema to use oneOf

- graphql-schemas/schema.yml
- schemas/app-sre/integration-sharding-1.yml
Remove `per-jira-board` sharding strategy because we want to use `static` instead.
Ticket: [APPSRE-11408](https://issues.redhat.com/browse/APPSRE-11408)
> :coffin: remove unused per-jira-board sharding strategy

- graphql-schemas/schema.yml
- schemas/aws/elasticache-defaults-1.yml
Add some service updates related fields to the Elasticache resource files.
Additionally, `auto_minor_version_upgrade` isn't required anymore and will default to `true`.
Ticket: [APPSRE-11432](https://issues.redhat.com/browse/APPSRE-11432)
> elasticache: add service updates related fields

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-target-1.yml
Saas triggers currently allow us to wait for a single image. However, in Konflux we cannot stuff multiple images into a single pipeline, i.e., we must wait for multiple images to wait.
We introduce the `images` field where tenants can specify a list of images to wait for. We keep the old `image` field for backwards compatibility. We will then gradually move `image` usage towards `images`. We will remove `image` once everything is migrated to new list schema.
> APPSRE-11326 support multiple image waits in saas

- graphql-schemas/schema.yml
- schemas/openshift/fleet-labels-1.yml
Schema for the Fleet Labeler Integration.
[Design doc](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/fleet-labeler.md?ref_type=heads)
[Example Use](https://gitlab.cee.redhat.com/service/sre-capabilities/-/merge_requests/2223)
Note, I would like to add this schema to main ahead of the integration implementation itself, as it would ease development by not needing to stay in sync with schema changes. Further, it helps to separate implementation into incremental PRs instead of single large PR. The schema does not change any existing behavior and is fully dedicated to fleet labeler, so merging ahead has no real downsides.
> APPSRE-11390 fleet labeler schema

- graphql-schemas/schema.yml
ie having externalResources deployed on that account
[APPSRE-11487](https://issues.redhat.com/browse/APPSRE-11487)
This will allow this type of queries:
```
{
accounts: awsaccounts_v1(filter: { name: "{{ accountRequest.name }}" }) {
name
terraformState {
provider
}
namespaces {
name
externalResources {
... on NamespaceTerraformProviderResourceAWS_v1 {
provisioner {
name
}
resources {
provider
identifier
output_resource_name
}
}
}
}
}
}
```
> APPSRE-11487 Allow to query namespaces related to an account

- schemas/aws/parameter-group-1.yml
In favor of Valkey 7+, we won't support Redis 7 anymore.
Ticket: [APPSRE-11489](https://issues.redhat.com/browse/APPSRE-11489)
> elasticache: drop redis 7 support

- graphql-schemas/schema.yml
- schemas/openshift/fleet-labels-spec-1.yml
- we use a single OCM instance. It will cover all current cases. Further, it simplifies logic as we do not need a mapping between clusters and ocms.
- More explicit naming: fleet-label-1 to fleet-label-spec-1. 
- `subscriptionLabels` are a json
> APPSRE-11390 fleet labeler fixes

- graphql-schemas/schema.yml
- schemas/app-sre/saas-file-target-1.yml
Time to say goodbye to `saas_file.resource_template.target.image` in favor of the new `images` (https://github.com/app-sre/qontract-schemas/pull/761).
All streams are aware if this change. App-interface data has been migrated to new `images` already.
> APPSRE-11544 remove saas target image

- graphql-schemas/schema.yml
- schemas/openshift/fleet-labels-spec-1.yml
Fleet labeler needs the subscription ID to properly set subscription labels for clusters.
> APPSRE-11390 store subscription_id in inventory

- schemas/access/bot-1.yml
- schemas/common-1.json
see rules in https://docs.gitlab.com/user/profile/
In particular this is important with project bots, with fancy names like `project_111131_bot_280c1319501ea648fc40189519f2d430`
related to APPSRE-11467
> Bot org_username needs to accept gitlab usernames

- schemas/openshift/cluster-1.yml
DTP labeling schema now contains dtp version. That makes it easier for us to stay backwards compatible, as we will see bigger label schema changes in DTP soon.
```
sre-capabilities.dtp.v{X}.{config-labels}
```
> APPSRE-11584 enforce DTP v2 labeling

- graphql-schemas/schema.yml
- schemas/openshift/fleet-labels-spec-1.yml
Fleet Labeler should use `OCMEnvironment` directly instead of going via `ClusterManager`. We currently have no need for any `ClusterManager` attributes.
This will also ease spec validation in Fleet Labeler, as OCMEnvironment is more strict in attributes.
> APPSRE-11583 Fleet Labeler use OCMEnv

- graphql-schemas/schema.yml
- schemas/aws/account-request-1.yml
The resulting account file path in app-interface must be configurable. This PR adds `accountFileTargetPath` to customize the path.
Ticket: [APPSRE-11540](https://issues.redhat.com/browse/APPSRE-11540)
> aws-account-request: add accountFileTargetPath

- graphql-schemas/schema.yml
- schemas/aws/account-1.yml
This PR adds `organizationAccountTags` to the `/aws/account-1.yml` schema. This enables the `aws-account-manager` to use this attribute to tag all accounts within a payer account with common tags, e.g. `cost-center: xxx`
Ticket: [APPSRE-11633](https://issues.redhat.com/browse/APPSRE-11633)
> :sparkles: aws-account: add organizationAccountTags

- schemas/metaschema-1.json
AFL - Automated Feature List
---
This MR adds optional title and description properties to `metaschema-1.json` child schemas. The MR also adds title and description pairs to `metaschema-1.json`, which are already defined in `/json-schema-spec-draft-06.json`.
The design doc did not include title field. I think it will be easier to source JSON/YAML property values versus depending on the filename and extracting the correct content.
> [AFL] Add optional title, description properties to metaschema

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
Default 5 mins is not enough for some RDS instances. Support `switchover_timeout` to customize it.
[APPSRE-11434](https://issues.redhat.com/browse/APPSRE-11434)
> [ERv2] support switchover timeout for blue/green deployment

- graphql-schemas/schema.yml
- schemas/openshift/openshift-cluster-manager-1.yml
https://issues.redhat.com/browse/APPSRE-11690
This setting allows to limit the number of concurrent upgrades within a sector.
We can the drop mutexes (only one upgrade at a time) and speed up upgrades on large sectors
> APPSRE-11690 new AUS sector setting: maxParallelUpgrades

- schemas/aws/terraform-resource-2.yml
Specify range in schema to avoid runtime error
```text
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateBlueGreenDeployment operation: The specified allocated storage of 10 is not valid. Specify an allocated storage value between 20 and 16384
```
[APPSRE-11434](https://issues.redhat.com/browse/APPSRE-11434)
> feat(erv2): limit allocated_storage range for blue_green_deployment

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
Related ticket: [APPSRE-11698](https://issues.redhat.com/browse/APPSRE-11698)
This adds the changes to schemas to enable [configuration of mTLS for ALB](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/configuring-mtls-with-elb.html)
The CA cert bundle will be stored in a S3 bucket that will be provided by tenant.
qontract-reconcile implementation: https://github.com/app-sre/qontract-reconcile/pull/4951
> ✨ Add alb mutual authentication APPSRE-11698

- schemas/openshift/terraform-output-format-1.yml
`.` is supported as secret data key name. Fix [mr](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/139441).
https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/#create-the-config-file
> fix: allow dot in secrete data fields

- schemas/aws/account-request-1.yml
Add pattern limit to aws account request name, to avoid error
```text
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateAccountAlias operation: The specified value for accountAlias is invalid. It must be a minimum length of 3 characters and maximum length of 63 characters, contain only digits, lowercase letters, and hyphens (-), but cannot begin or end with a hyphen. 
```
[APPSRE-11882](https://issues.redhat.com/browse/APPSRE-11882)
> fix(account-request): limit name pattern to match aws alias

- graphql-schemas/schema.yml
- schemas/app-sre/app-1.yml
- schemas/gcp/project-1.yml
[APPSRE-11221](https://issues.redhat.com/browse/APPSRE-11221)
Adds Artifact Registry support to App-Interface. This is necessarily a breaking change due to renaming of existing properties to conform both AR & GCR support (although GCR is now just using AR under the hood and proxied to the existing gcr.io endpoints).
QR PR: https://github.com/app-sre/qontract-reconcile/pull/4931
> Breaking change that adds Artifact Registry support to App Interface

- graphql-schemas/schema.yml
- schemas/dependencies/jira-board-1.yml
Refactor the `/dependencies/jira-board-1.yml` definition and replace the `issueSecurityId` attribute with a general `issueFields` one.
This allows us to add and verify any arbitrary Jira issue field via `jira-permissions-validator` and `jiralert`, e.g., the new `Work Type` attribute.
Ticket: [APPSRE-12034](https://issues.redhat.com/browse/APPSRE-12034)
> :recycle: jira-board: introduce general issue fields attribute

- schemas/json-schema-spec-draft-06.json
- schemas/metaschema-1.json
This MR adds `externalDocumentation` attributes to the top-level metaschema and nested schema properties.
Inspired by discussion on documentation for AWS ASG schema - cc https://github.com/app-sre/qontract-schemas/pull/869#discussion_r2168498804.
Example: `schemas/aws/asg-defaults-1.yml`
```yaml
"$schema": /metaschema-1.json
version: '1.0'
type: object
title: "ASG Defaults"
description: |
Schema for defining default configuration values for AWS Auto Scaling Groups (ASGs).
This schema enables teams to specify baseline settings for scaling, instance types,
networking, security, and lifecycle management. These defaults are used to ensure
consistent and reliable ASG deployments across environments.
externalDocumentation: |
https://docs.aws.amazon.com/autoscaling/
additionalProperties: false …
```
> Introduce externalDocumentation attribute

- schemas/aws/account-1.yml
- schemas/common-1.json
use pattern from aws doc https://docs.aws.amazon.com/accounts/latest/reference/API_AlternateContact.html
This field is introduced in https://github.com/app-sre/qontract-schemas/pull/663, and only used by aws account, so remove it from common and apply aws format here.
[APPSRE-12218](https://issues.redhat.com/browse/APPSRE-12218)
> fix(account): use same regex as aws api for phoneNumber

- graphql-schemas/schema.yml
Drop `name` uniqueness to support inline and referenced `/dependencies/glitchtip-project-alert-1.yml`. Qontract-server can't handle it `Cannot return null for non-nullable field GlitchtipProjectAlert_v1.name`. Nevertheless, we can live without the uniqueness; in the worst case, a Glitchtip project overrides its own alerts.
> :bug: glitchtip-alert: drop uniqueness

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
To fix this [error](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/151341/diffs#note_16951660
) message on reconcile:
```
(...) api error ValidationError: Mutual Authentication mode passthrough does not support trust store
```
> Fix make it so CA bundle is only required on verify mode

- graphql-schemas/schema.yml
`path` and `schema` missing
```
qontract-server               | /opt/app-root/src/node_modules/graphql/type/validate.js:71
qontract-server               |     throw new Error(errors.map(function (error) {
qontract-server               |           ^
qontract-server               |
qontract-server               | Error: Interface field DatafileObject_v1.schema expected but AppQuayRepos_v1 does not provide it.
```
> fix quay repo schema

- graphql-schemas/schema.yml
- schemas/aws/terraform-resource-2.yml
The idea is to be able to create templated secrets to copy from Vault to AWS Secrets Manager
This work is needed in the context of APPSRE-12414, since AWS expects the RDS credentials for AWS RDS Proxy in a defined format that cannot be configured.
> Add secret_format to AWS Secrets Manager
