graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml
schemas/app-sre/pipelines-provider-1.yml
schemas/app-sre/saas-file-2.yml
schemas/app-sre/tekton-object-template-1.yml
schemas/common-1.json
schemas/openshift/deploy-resources-1.yml
schemas/openshift/resource-requirements-1.yml

openshift-tekton-integration schema changes

---

schemas/openshift/cluster-1.yml

Add all load_balancer possible values

---

schemas/aws/rds-defaults-1.yml

allow config publicly_accessible for rds

---

schemas/aws/rds-defaults-1.yml

add timeouts for rds

---

schemas/openshift/terraform-resource-1.yml

add timeouts in rds overrides

---

graphql-schemas/schema.yml
schemas/dependencies/dyn-traffic-director-1.yml

Ref.: https://issues.redhat.com/browse/APPSRE-3884
Required for https://github.com/app-sre/qontract-reconcile/pull/1965

introduce new schema dyn-traffic-director

---

graphql-schemas/schema.yml
schemas/access/user-1.yml

part of https://issues.redhat.com/browse/APPSRE-4122

add support to define alternate aws username

---

schemas/aws/elasticsearch-defaults-1.yml

add elasticsearch-defaults

---

schemas/aws/elasticsearch-defaults-1.yml

fix elasticsearch-defaults

---

graphql-schemas/schema.yml
schemas/openshift/terraform-resource-1.yml

part of https://issues.redhat.com/browse/APPSRE-3925

add tf provider secrets-manager

---

schemas/app-sre/saas-file-2.yml

I had wrongly calculated the max size
Part of APPSRE-3389

Set saas file 2 max length to 39

---

graphql-schemas/schema.yml
schemas/openshift/terraform-resource-1.yml

add assume_service to aws-iam-role

---

graphql-schemas/schema.yml
schemas/openshift/terraform-resource-1.yml

Related to APPSRE-3695
Required for https://github.com/app-sre/qontract-reconcile/pull/2043

add idle_timeout support for AWS ALB

---

graphql-schemas/schema.yml
schemas/aws/account-1.yml

part of https://issues.redhat.com/browse/APPSRE-4186
this PR adds the schema changes required to define resources that are approved to be deleted for a specified time duration.

add support to delete specific aws resources

---

graphql-schemas/schema.yml

following https://issues.redhat.com/browse/APPSRE-2694

make aws account queriable by name

---

graphql-schemas/schema.yml
schemas/aws/asg-defaults-1.yml
schemas/openshift/terraform-resource-1.yml

part of https://issues.redhat.com/browse/APPSRE-3925

add terrafrom asg

---

graphql-schemas/schema.yml
schemas/openshift/namespace-1.yml
schemas/openshift/shared-resources-1.yml

[openshift-serviceaccount-tokens] add support to define resource output name

---

graphql-schemas/schema.yml
schemas/access/role-1.yml

Editing schema to include an expirationDate field. Work is part of ticket [APPSRE-2284](https://issues.redhat.com/browse/APPSRE-2284)
Signed-off-by: Suzana Nesic <snesic@redhat.com>

Adding expirationDate to the schemas

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-1.yml
schemas/app-sre/saas-file-2.yml

Related: https://github.com/app-sre/qontract-reconcile/pull/2005

APPSRE-3446: Add parent_config_sha attribute

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

part of https://issues.redhat.com/browse/APPSRE-3991

support insecure-skip-tls-verify

---

graphql-schemas/schema.yml
schemas/openshift/namespace-1.yml

Ref: https://issues.redhat.com/browse/APPSRE-4195

enable namespaces to apply resources with cluster admin permissions

---

.gitignore
Makefile
pr_check.sh

this will add a pr-check script that will be executed in every PR to this repo.
this will perform a basic check of the schemas, without any data that uses them.

introduce pr-check with qontract-validator

---

graphql-schemas/schema.yml
schemas/openshift/terraform-resource-1.yml

JIRA: APPSRE-3695
qontract-reconcile changes: https://github.com/app-sre/qontract-reconcile/pull/2098
Make HTTP methods explicit in the ALB config

Make HTTP methods explicit in ALB config

---

graphql-schemas/schema.yml
schemas/app-sre/app-1.yml
schemas/common-1.json
schemas/dependencies/endpoint-monitoring-provider-1.yml

Schema changes for blackbox-exporter based service endpoint monitoring
Ref: https://issues.redhat.com/browse/APPSRE-4161

[endpoint monitoring] Schema enhancement for endpoint monitoring with blackbox-exporter

---

schemas/common-1.json
test/test_sql_regexp.py

Reverts app-sre/qontract-schemas#58

Revert "Improve sql query validator pattern"

---

schemas/aws/account-1.yml

https://issues.redhat.com/browse/ASIC-168

allow disabling terraform-users

---

schemas/aws/elasticsearch-defaults-1.yml

Missing from #56
part of APPSRE-4219

Add documentation to master_user_secret ES option

---

schemas/common-1.json
test/test_sql_regexp.py

* Regex now accepts comments in both formats `-- comment \n` and `/* comment */`
* `*` is now allowed in comments and in values, e.g: `where id='an_id_with_*'`

Improve SQL query regexp

---

graphql-schemas/schema.yml
schemas/app-sre/app-1.yml

Field was replaced by grafanaUrls

Remove field grafanaUrl

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

explicit aws infra account for cluster and cluster vpc peering acceptor

---

graphql-schemas/schema.yml
schemas/aws/asg-defaults-1.yml
schemas/openshift/terraform-resource-1.yml

move image id from default file to namespace file

---

graphql-schemas/schema.yml
schemas/aws/policy-1.yml

part of https://issues.redhat.com/browse/APPSRE-3251
with this change, we can implement a validation in qontract-reconcile.

add support to define aws policy as mandatory

---

README.md
schemas/access/role-1.yml

- Add docs on crossref definitions

Add docs on crossref usage/definition

---

schemas/access/role-1.yml

Fix schema for `owned_saas_files` in `role-1` definition

APPSRE-3341: Fix owned_saas_files json schema definition

---

graphql-schemas/schema.yml
schemas/openshift/terraform-resource-1.yml

Part of https://issues.redhat.com/browse/APPSRE-3925
Design doc: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/34670

add image_data

---

graphql-schemas/schema.yml
schemas/openshift/terraform-resource-1.yml

[APPSRE-4674](https://issues.redhat.com/browse/APPSRE-4674)
add condition context keys for IAM and AWS STS https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html

add assume_condition

---

graphql-schemas/schema.yml

part of https://issues.redhat.com/browse/APPSRE-4663
follows up on #93 
this will allow us to query the different cluster auth providers differently.

make cluster auth an interface

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

implemented in https://github.com/app-sre/qontract-reconcile/pull/2238

APPSRE-4029 add a locking system to avoid simultaneous cluster upgrades

---

graphql-schemas/schema.yml
schemas/app-sre/environment-1.yml
schemas/app-sre/saas-file-1.yml
schemas/app-sre/saas-file-2.yml
schemas/app-sre/vault-secret-parameter-1.yml

part of https://issues.redhat.com/browse/APPSRE-4716

add support for saas file secret parameters

---

graphql-schemas/schema.yml

part of https://issues.redhat.com/browse/APPSRE-4716
fixes #101

add missing secretParameters to graphql schema

---

schemas/openshift/prometheus-rule-1.yml

to support additional jira boards.

remove jiralert enum

---

graphql-schemas/schema.yml

fix isUnique typo

---

graphql-schemas/schema.yml
schemas/app-sre/escalation-policy-1.yml

part of https://issues.redhat.com/browse/APPSRE-4754

make jiraBoard mandatory in escalation policy

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-2.yml

Missed a spot from: https://github.com/app-sre/qontract-schemas/pull/112

Optional slack property for saasfilev2

---

README.md
graphql-schemas/schema.yml
schemas/access/role-1.yml
schemas/app-sre/saas-file-1.yml

Reverts app-sre/qontract-schemas#122

Revert "APPSRE-3556 deprecate saas-file-1"

---

schemas/app-sre/contract-1.yml
schemas/app-sre/contract-version-1.yml
schemas/app-sre/sre-checkpoint-1.yml

part of [APPSRE-4788](https://issues.redhat.com/browse/APPSRE-4788)
This is an implementation of the accepted proposal from @maorfr in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/32536.
It adds the link to the SRE checkpoint schema. This is optional for the moment, I will make it mandatory once I have updated all the checkpoint files.

Added contract related schemas

---

schemas/app-sre/contract-version-1.yml

This was missing from #118
part of APPSRE-4788
Signed-off-by: Rafael Porres Molina <rporres@gmail.com>

Add missing field from contract version

---

schemas/openshift/terraform-resource-1.yml

defined in https://github.com/app-sre/qontract-schemas/blob/main/schemas/aws/s3-1.yml#L34-L53

remove duplicated definition

---

graphql-schemas/schema.yml
schemas/openshift/terraform-resource-1.yml

https://issues.redhat.com/browse/APPSRE-4651

add secrets-manager-service-account

---

graphql-schemas/schema.yml
schemas/app-sre/integration-1.yml
schemas/app-sre/integration-spec-1.yml

part of https://issues.redhat.com/browse/APPSRE-2963
design document: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/qontract-operator.md
this PR adds schema changes to allow defining how integrations should be operated.
for example, how much resources does the integration needs.
since integrations can run in multiple environments/namespaces, `managed` is a list which includes a reference to a namespace.
this PR is essentially a copy of the fields we pass to the qontract-reconcile helm chart: https://github.com/app-sre/qontract-reconcile/tree/master/helm#configuration

manage integrations

---

graphql-schemas/schema.yml

part of https://issues.redhat.com/browse/APPSRE-2963

fix dashdotdb typo in integration spec

---

graphql-schemas/schema.yml

follows up on #133
this is not used in any code path, so should be safe to merge with no further dependencies.

update app -> saas file backref

---

graphql-schemas/schema.yml
schemas/app-sre/integration-spec-1.yml

part of https://issues.redhat.com/browse/APPSRE-2963

extraEnv from object to list of objects

---

schemas/aws/asg-defaults-1.yml

part of https://issues.redhat.com/browse/APPSRE-5501

add vpc_zone_identifier for asg

---

schemas/aws/asg-defaults-1.yml

part of https://issues.redhat.com/browse/APPSRE-5501

remove availability_zones for asg

---

graphql-schemas/schema.yml
schemas/app-sre/slo-document-1.yml

this will allow to find out in a simple way if an app has an slo document.

add app as mandatory field to slo document

---

graphql-schemas/schema.yml
schemas/app-sre/slo-document-1.yml

make app required in slo-document

---

schemas/aws/terraform-resource-2.yml

part of https://issues.redhat.com/browse/APPSRE-5711
terraform-resource-2 has grown stale not being merged for a while in #87

update terraform-resource-2 from terraform-resource-1

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

Related: 
- https://github.com/app-sre/qontract-reconcile/pull/2425
- https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/39783

Add OCM product specific clusters

---

schemas/aws/account-1.yml
schemas/openshift/cluster-1.yml

part of https://issues.redhat.com/browse/APPSRE-2963
follows up on https://github.com/app-sre/qontract-reconcile/pull/2461

remove terraform wrapper integrations

---

schemas/aws/account-1.yml

part of https://issues.redhat.com/browse/APPSRE-5885

allow disabling terraform-aws-route53 per aws account

---

schemas/aws/terraform-resource-2.yml

This MR addresses run-time validation errors with the recently added rosa-authenticator schema update.

rosa-authenticator schema bugfixes

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

https://coreos.slack.com/archives/C03AKQD1SHF/p1656389106089519

add vpc_arn property to rosa-authenticator

---

schemas/access/bot-1.yml
schemas/common-1.json

related to https://issues.redhat.com/browse/APPSRE-4866

enable defining github username for bots to end with [bot]

---

graphql-schemas/schema.yml
schemas/dependencies/jira-board-1.yml

This is part of Jiralert auto resolve issue feature. We need the resolve state for each board defined.
https://issues.redhat.com/browse/APPSRE-5879

Add issueResolveState for jira-board

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

Reverts app-sre/qontract-schemas#192
There might be a problem with this. I'll investigate more next week.

Revert "(fedramp) rosa-authenticator: add new certificate_arn and domain_name properties"

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

I reverted the original PR because I thought it was maybe broken. Now I've learned the original PR is fine. So I am reverting the revert. :) 
Reverts app-sre/qontract-schemas#193

Revert "Revert "(fedramp) rosa-authenticator: add new certificate_arn and domain_name properties""

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

request: https://coreos.slack.com/archives/C03AKQD1SHF/p1658244721379869

Update rosa auth to accomodate latest developments

---

graphql-schemas/schema.yml

remove unused definitions

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

driver: https://coreos.slack.com/archives/C03AKQD1SHF/p1658273064528059

Include rosa-auth-vpce resource

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

driver: https://coreos.slack.com/archives/C03AKQD1SHF/p1658345670364989

add back presignup url

---

graphql-schemas/schema.yml
schemas/vault-config/auth-1.yml

Note: this change will have no effect on commercial as OIDC is not yet utilized.
ticket: https://issues.redhat.com/browse/APPSRE-6072

Refactor vault oidc auth settings

---

graphql-schemas/schema.yml

prerequisite for https://github.com/app-sre/qontract-reconcile/pull/2664
APPSRE-6089

PermissionQuayOrgTeam_v1: add backref to roles

---

schemas/aws/elasticsearch-defaults-1.yml

add field for ebs_options

---

schemas/app-sre/app-1.yml

for services going through an offboarding, we should have an indication for it.
this will be followed up with documentation updates.

add onboarding status: offboarding

---

graphql-schemas/schema.yml

Reverts app-sre/qontract-schemas#227
detected a bug during rollout. reverting for now

Revert "resolvable resource references for openshift-resources"

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

APPSRE-6126
design doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/terraform-asg-ami-selection.md

terraform-resource: enhance aws asg ami image selection

---

graphql-schemas/schema.yml
schemas/aws/kinesis-defaults-1.yml
schemas/aws/terraform-resource-2.yml

[APPSRE-6069] add kinesis-to-opensearch lambda schemas

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml

app-interface-settings: add jiraWatcher timeout settings

---

schemas/aws/elasticsearch-defaults-1.yml

[APPSRE-6069] add warm config for elasticsearch

---

schemas/aws/kinesis-defaults-1.yml

update kinesis maximum retention_period

---

schemas/aws/kinesis-defaults-1.yml

add batch config to kinesis-defaults

---

graphql-schemas/schema.yml
schemas/aws/account-1.yml
schemas/dependencies/rosa-aws-1.yml
schemas/openshift/cluster-1.yml

Add ROSA clusters related attributes 
Related: https://github.com/app-sre/qontract-reconcile/pull/2752

Add attributes related to Rosa clusters

---

schemas/access/role-1.yml

required for https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/47997

add cluster and aws account as targets for change type data files

---

graphql-schemas/schema.yml
schemas/app-sre/integration-1.yml
schemas/app-sre/integration-spec-1.yml

Related ticket: https://issues.redhat.com/browse/APPSRE-6100

Add shardSpecOverride to IntegrationSpec

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

related to https://issues.redhat.com/browse/APPSRE-4709
same as #252, but for `mutexes` instead of `workloads`.

add allowed mutexes to ocm schema

---

graphql-schemas/schema.yml
schemas/cloudflare/account-1.yml
schemas/cloudflare/terraform-resource-1.yml
schemas/openshift/external-resource-1.yml

Adds multiple schemas to support Cloudflare resources
Schemas added:
- CloudflareAccount_v1
- CloudflareZoneArgo_v1
- CloudflareZoneRecord_v1
- CloudflareZoneWorker_v1
- CloudflareZoneWorkerScript_v1
- Cloudflare provider for NamespaceExternalResource_v1
Part of: https://issues.redhat.com/browse/APPSRE-5715

Introduce Cloudflare provider & resources

---

graphql-schemas/schema.yml
schemas/app-sre/integration-1.yml
schemas/app-sre/integration-shardspec-override-1.yml

Make it possible to override the image for Merge Request checks

APPSRE-6321 Add ShardSpecOverride to MR checks

---

schemas/app-interface/prometheus-rule-test-1.yml

Introduce target_clusters to prometheus_rules_tester

---

graphql-schemas/schema.yml

cleanup configurable resources

---

schemas/access/role-1.yml

enable usage of change types to define ownership over saas file target files.
ref: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/48797

add saas file target as an allowed schema reference of datafiles

---

graphql-schemas/schema.yml

add datafile field to graphql scehma for cluster and aws account

---

schemas/aws/rds-defaults-1.yml

use false as the only value for auto_minor_version_upgrade parameter

---

graphql-schemas/schema.yml
schemas/cloudflare/terraform-resource-1.yml

Please see the ticket for more context including the PR for qontract-reconcile and other documentation.
Related to: https://issues.redhat.com/browse/APPSRE-6289

Add support for Cloudflare certificates

---

graphql-schemas/schema.yml
schemas/vault-config/role-1.yml

ticket: https://issues.redhat.com/browse/APPSRE-6389
Supports https://github.com/app-sre/vault-manager/pull/84

Include optional attribute to output approle credentials at specified vault path

---

graphql-schemas/schema.yml

change-type searchable by name

---

graphql-schemas/schema.yml
schemas/access/role-1.yml

related to https://issues.redhat.com/browse/APPSRE-6324
required for https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/49963

enable self-service for gabi instances

---

graphql-schemas/schema.yml
schemas/access/role-1.yml
schemas/app-interface/app-interface-settings-1.yml
schemas/app-sre/app-1.yml
schemas/common-1.json
schemas/dependencies/glitchtip-instance-1.yml
schemas/dependencies/glitchtip-organization-1.yml
schemas/dependencies/glitchtip-team-1.yml

This implements the schema for the qontract-reconcile [glitchtip](https://gitlab.com/glitchtip/glitchtip-backend) integration.
Ticket: [APPSRE-6260](https://issues.redhat.com/browse/APPSRE-6260)
Design Doc: [Glitchtip](https://gitlab.cee.redhat.com/cassing/app-interface/-/blob/master/docs/app-sre/design-docs/glitchtip.md)

glitchtip schemas

---

graphql-schemas/schema.yml
schemas/app-interface/change-type-1.yml

part of https://issues.redhat.com/browse/APPSRE-6474
Attache a priority to change-types that will influence how merge requests are processed.

introduce change-type priority

---

schemas/openshift/cluster-1.yml

Allow Ocm integrations in the cluster's spec disable attribute

Allow OCM integrations disablement at cluster level

---

graphql-schemas/schema.yml
schemas/access/role-1.yml

user self-service i said

---

schemas/openshift/cluster-1.yml
schemas/openshift/cluster-upgrade-policy-1.yml

easier management. this doesn't introduce any functional changes.

extract cluster upgrade policy to separate schema

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

- Add ROSA Hosted CP Attributes

Add ROSA Hosted CP Required attributes

---

graphql-schemas/schema.yml
schemas/aws/asg-defaults-1.yml
schemas/aws/terraform-resource-2.yml

replace https://github.com/app-sre/qontract-schemas/pull/309

enhance config for asg

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

related story: https://issues.redhat.com/browse/APPSRE-6543

Add properties for recommended versions

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-2.yml

APPSRE-4670
Signed-off-by: Rafael Porres Molina <rporres@gmail.com>

Allow saas file timeouts > 60 minutes

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

Allows for a recommended version per workload

Recommended version should be a list.

---

graphql-schemas/schema.yml
schemas/cloudflare/account-1.yml

Reverts app-sre/qontract-schemas#318
A new MR will be created to add this field as well as another field which was missing in this PR

Revert "add 2fa enforcement support to cloudflare account schema"

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

This reverts commit bf8fdd33a36047754901b62566f82ee5061795f2.

Revert "cluster.auth attribute becomes a list of objects instead of a single object (#317)"

---

graphql-schemas/schema.yml
schemas/openshift/cluster-upgrade-policy-1.yml
schemas/openshift/openshift-cluster-manager-1.yml

Implement sector handling in cluster upgrade policies
See https://issues.redhat.com/browse/APPSRE-6545

APPSRE-6545 cluster upgrade policy sector

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml

it has not been used in a long time: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8920

remove pullRequestGateway

---

graphql-schemas/schema.yml
schemas/app-sre/integration-spec-1.yml

Corresponding with https://github.com/app-sre/qontract-reconcile/pull/2996, add a new, optional fluentdResources section to integration specs.
[APPSRE-6600](https://issues.redhat.com/browse/APPSRE-6600)

Add fluentdResources to integration spec

---

graphql-schemas/schema.yml
schemas/app-sre/app-1.yml
schemas/openshift/namespace-1.yml
schemas/openshift/shared-resources-1.yml

follow up on #332
- add ability to query all glitchtip projects
- make glitchtip projects reference only (no inline)
- add backrefs to find namespaces and shared resources from glitchtip project

glitchtip queries adjustments

---

schemas/cna/aws-rds-config-1.yml

username isnt optional in the module

rds required fields

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

Enhance `cluster.auth.oidc` schema.
APPSRE-6622

OIDC IDP cluster auth object

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

required for https://github.com/app-sre/qontract-reconcile/pull/3000
this field will be used by the integration to determine which clusters to act on.

add clusterAdmin property to cluster files

---

graphql-schemas/schema.yml

fixes #345
@cubismod i wonder how this wasn't caught in pr-check following #269

schema fixes for self-service

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

Along with this add initialVersion, that can be used by fleetmanagers to provision new clusters.

APPSRE-6644 Add channel to recommended version

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

Reverts app-sre/qontract-schemas#349

Revert "APPSRE-6644 Add channel to recommended version"

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

Enhance `cluster.auth.oidc` schema.
APPSRE-6622
Reapply reverted commits:
- OIDC cluster auth (#341)
- make issuer as non-required field in cluster.auth.service OIDC (#350)

cluster auth oidc

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

Redo https://github.com/app-sre/qontract-schemas/pull/349
Along with this add initialVersion, that can be used by fleetmanagers to provision new clusters.

Rv add openshift version

---

graphql-schemas/schema.yml
schemas/app-sre/integration-spec-1.yml

helm determined 0 as false when rendering the template.

fix sleepDurationSec type

---

graphql-schemas/schema.yml
schemas/vault-config/instance-1.yml
schemas/vault-config/replication-1.yml
schemas/vault-config/replication-paths-1.yml

[APPSRE-6137](https://issues.redhat.com/browse/APPSRE-6137)
[Design doc](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/vault-replica-integration.md#proposal)

Add schema changes for Vault Replication

---

graphql-schemas/schema.yml

will this fix the errors we are seeing in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/54909?

add datafile attribute to permission interface implementations

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

https://issues.redhat.com/browse/APPSRE-6756
this schema will be used to trigger jobs in jenkins following an upgrade of an addon for all clusters within an OCM org.

addon upgrade tests

---

graphql-schemas/schema.yml
schemas/vault-config/replication-paths-1.yml

Add schemas to support Vault Replication from a policy
Code changes: [Qontract-Reconcile PR](https://github.com/app-sre/qontract-reconcile/pull/3113)

Add schemas to support Vault Replication from a policy

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

https://issues.redhat.com/browse/APPSRE-6790
Flag enabling OCM addon upgrade policy management
See also https://github.com/app-sre/qontract-reconcile/pull/3120

APPSRE-6790 addon upgrade policies management

---

schemas/aws/terraform-resource-2.yml

This MR completes adding SMS as a subscription type for SNS.

Allow sms as subscription type

---

graphql-schemas/schema.yml
schemas/dependencies/skupper-network-1.yml
schemas/openshift/cluster-1.yml
schemas/openshift/namespace-1.yml

Schemas enhancement for the skupper integration
Ticket: [APPSRE-6515](https://issues.redhat.com/browse/APPSRE-6515)
Design doc: [skupper-integration](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/skupper-integration.md)

skupper schema

---

graphql-schemas/schema.yml
schemas/dependencies/jenkins-instance-1.yml

https://issues.redhat.com/browse/APPSRE-6798

add workerFleets to jenkins-instance

---

graphql-schemas/schema.yml
schemas/openshift/jump-host-1.yml

cc @BumbleFeng 
Corresponding change in qr: https://github.com/app-sre/qontract-reconcile/pull/3187

APPSRE-6609 add jumphost remotePort

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

add option to configure ingress cidr blocks for alb

terraform alb ingress cidr blocks

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

part of https://issues.redhat.com/browse/APPSRE-7044

allow enable/disable http2 for alb

---

graphql-schemas/schema.yml
schemas/vault-config/auth-1.yml

Add vault config support for kubernetes auth

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-2.yml

Related to: [APPSRE-4355](https://issues.redhat.com/browse/APPSRE-4355)

Add managed resource names to Saas file

---

graphql-schemas/schema.yml

since we have zone based state.

Remove unique requirement for Cloudflare DNS records

---

graphql-schemas/schema.yml
schemas/vault-config/role-1.yml

APPSRE-7074
Note: incoming changes do not affect existing resources within ai

Add support for vault kubernetes roles

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

Enables Rosa-Authenticator resources to accept an optional list of urls called "insights_callback_urls".

[APPSRE-7130] [FedRAMP] support optional "insights_callback_urls" objects for rosa-authenticator resources

---

schemas/openshift/cluster-1.yml

See https://github.com/app-sre/qontract-reconcile/pull/3233

allow disable route53 integration

---

graphql-schemas/schema.yml
schemas/access/role-1.yml
schemas/access/user-1.yml
schemas/app-interface/app-interface-settings-1.yml
schemas/cloudflare/account-role-1.yml

An example usage of the schema https://gitlab.cee.redhat.com/app-sre/app-interface-dev-data/-/merge_requests/39

Add necessary schemas for cloudflare user management

---

graphql-schemas/schema.yml
schemas/vault-config/auth-1.yml

[vault] include attributes to support inter cluster auth

---

graphql-schemas/schema.yml
schemas/vault-config/auth-1.yml

Update vault kube auth definition to retrieve ca from specified vault path

Vault kube auth ca cert

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-target-1.yml

Introduce dynamic selection of namespace (`resourceTemplates.targets.namespaceSelector`) in saas files.
Design doc: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/59689
Ticket: [APPSRE-7124](https://issues.redhat.com/browse/APPSRE-7124)

[saas-namespace-selector] SaaS File namespaceSelector

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

https://issues.redhat.com/browse/APPSRE-7273
Implemented in https://github.com/app-sre/qontract-reconcile/pull/3297

optional field in externalResource.account-tgw: manageRoute53Associations

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-target-1.yml

This needs an adapted saasherder first which will be introduced later this month.

Revert "[saas-namespace-selector] SaaS File namespaceSelector (#395)"

---

graphql-schemas/schema.yml
schemas/cloudflare/terraform-resource-1.yml

Adds ability to set [tiered_cache](https://registry.terraform.io/providers/cloudflare/cloudflare/3.32.0/docs/resources/tiered_cache) on a zone
Ref.: https://issues.redhat.com/browse/APPSRE-7363

tf-cloudflare-resources: add tiered_cache cache_type setting

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-target-1.yml

Introduce dynamic selection of namespace (`resourceTemplates.targets.namespaceSelector`) in saas files.
Design doc: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/59689
Ticket: [APPSRE-7124](https://issues.redhat.com/browse/APPSRE-7124)

saas namespace selector

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml
schemas/cloudflare/dns-zone-1.yml

- Add max_records to zone
- Add default max records to App Interface settings

Adding soft limit for Cloudflare DNS zone

---

graphql-schemas/schema.yml
schemas/app-sre/integration-spec-1.yml
schemas/openshift/cluster-1.yml

part of https://issues.redhat.com/browse/APPSRE-7589

remove e2e-tests

---

schemas/aws/terraform-resource-2.yml

AWS RDS - db.m7g instances

---

graphql-schemas/schema.yml
schemas/aws/terraform-repo-1.yml

[APPSRE-7061](https://issues.redhat.com/browse/APPSRE-7061)
New schema for a Terraform Repo which is not associated with a namespace but rather an AWS account. This is separate from a "Terraform Resource" which is handled by Terrascript and a separate integration. 
Corresponding design doc: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/58341#note_5807974

Terraform Repo Schema

---

schemas/aws/terraform-resource-2.yml

- db.t3.large
- db.t3.xlarge
- db.t3.2xlarge

add new t3 RDS instances classes

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-2.yml
schemas/aws/account-1.yml
schemas/aws/cleanup-option-1.yml
schemas/common-1.json

Add aws cleanup schema

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

$SUBJECT
Related integration changes: https://github.com/app-sre/qontract-reconcile/pull/3536
This benefits the work in https://issues.redhat.com/browse/SDE-2715

tf-resources: add access_logs field to aws alb schema

---

schemas/common-1.json
test/test_sql_regexp.py

We want to allow more queries to accommodate for database post-upgrade queries. Specifically allow:
- ANALYZE
- VACUUM
- REINDEX

APPSRE-6899 extend sql query whitelist

---

graphql-schemas/schema.yml
schemas/aws/terraform-repo-1.yml

https://issues.redhat.com/browse/APPSRE-7732
Dependency for https://github.com/app-sre/qontract-reconcile/pull/3544

Add support for optional module dependencies within terraform-repo

---

graphql-schemas/schema.yml
schemas/aws/terraform-repo-1.yml

This reverts commit 7047cbb67346a23510709624ab39b23deb155174.

Revert "update tf-repo to support optional module dependencies (#458)"

---

graphql-schemas/schema.yml
schemas/aws/msk-defaults-1.yml
schemas/aws/terraform-resource-2.yml

Schemas to support AWS MSK
Ticket: [APPSRE-7534](https://issues.redhat.com/browse/APPSRE-7534)

[Apache Managed Streaming for Kafka] MSK schemas

---

schemas/app-interface/prometheus-rule-test-1.yml

Remove target_clusters as it is not longer used

---

graphql-schemas/schema.yml
schemas/access/role-1.yml

https://issues.redhat.com/browse/APPSRE-7806

enable self-service for aws group and policy

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

Support the creation of multiple MSK SASL/SCRAM users.

[terraform msk] multi user support

---

schemas/aws/account-1.yml

Add `terraform-tgw-attachments` to the list so it can be disabled

Enable terraform-tgw-attachments to be disabled

---

schemas/app-sre/pipelines-provider-1.yml
schemas/app-sre/tekton-pipeline-template-1.yml
schemas/app-sre/tekton-provider-defaults-1.yml
schemas/app-sre/tekton-task-template-1.yml

part of [APPSRE-6031](https://issues.redhat.com/browse/APPSRE-6031)

Limit the name length of the the pipelines

---

graphql-schemas/schema.yml
schemas/app-sre/escalation-policy-1.yml

part of https://issues.redhat.com/browse/APPSRE-4926
this will expose the data to pass on to jiralert to create automated tickets.

add jira component field to escalation policy

---

schemas/dependencies/slack-workspace-1.yml

Add Slack support for sd-app-sre-alert-report

---

graphql-schemas/schema.yml
schemas/dependencies/status-board-1.yml

Adding status-board schema to support writing app-interface product/application data to status-board.

Add schema for status board export integration

---

graphql-schemas/schema.yml
schemas/app-sre/integration-1.yml
schemas/app-sre/integration-shard-spec-override-1.yml
schemas/app-sre/integration-sharding-1.yml

Re-introduce shardSpecOverrides to PR_CHECK

---

graphql-schemas/schema.yml
schemas/access/role-1.yml

make query-validation datafiles potentially self-serviceable via change-types and roles
https://issues.redhat.com/browse/APPSRE-7962
Signei-off-by: Gerd Oberlechner <goberlec@redhat.com>

query-valiadation self-service

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

Add `ocmSubscriptionLabels` attribute to `/openshift/cluster-1.yml` schema.
Design-doc: [cluster-ocm-labels](https://gitlab.cee.redhat.com/service/app-interface/-/blob/5fb4ba1319fe1f6782e74644db1445a945b30e59/docs/app-sre/design-docs/cluster-ocm-labels.md)
Ticket: [APPSRE-8073](https://issues.redhat.com/browse/APPSRE-8073)

[cluster] ocmSubscriptionLabels attribute

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

This should enable configuring autoscaling for machine pools.
[APPSRE-7899](https://issues.redhat.com/browse/APPSRE-7899)

Add autoscaling properties to machine pool

---

graphql-schemas/schema.yml
schemas/access/role-1.yml
schemas/app-interface/app-interface-settings-1.yml
schemas/common-1.json

Enhance the schemas and add attributes needed for the new ldap-groups integration:
- [/access/role-1.yml] add ldapGroup attribute
- [/app-interface/app-interface-settings-1.yml] ldapGroups attribute

[ldap groups] attributes

---

graphql-schemas/schema.yml
schemas/app-sre/slo-document-1.yml

Change prometheus reference to allow external prometheus configuration.
Required for: https://issues.redhat.com/browse/APPSRE-8197

Add external configuration to enable RHOBS access

---

graphql-schemas/schema.yml
schemas/app-sre/slo-document-1.yml

Reverts app-sre/qontract-schemas#501

Revert "Add external configuration to enable RHOBS access"

---

graphql-schemas/schema.yml
schemas/dependencies/dynatrace-environment-1.yml

Add apiToken to DT dependency
```
---
$schema: /dependencies/dynatrace-environment-1.yml
...
apiToken:
path: path/to/token
field: token-field
```
Follow-up of https://github.com/app-sre/qontract-schemas/pull/492

APPSRE-8144 add apiToken for dt

---

graphql-schemas/schema.yml

Token is a map -> not hashable -> cannot be unique

APPSRE-8144 unique not hashable

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

- [cluster] remove obsolete OIDC attributes
- [cluster ocmSubscriptionLabels] update sre-capabilities.rhidp label structure
Ticket: [APPSRE-8126](https://issues.redhat.com/browse/APPSRE-8126)

[rhidp] decommission app interface flavor

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

Reverts app-sre/qontract-schemas#510

Revert "[rhidp] decommission app interface flavor"

---

schemas/openshift/cluster-1.yml

Needed for https://github.com/app-sre/qontract-reconcile/pull/3775
Reverts #511 and replaces #510

[cluster ocmSubscriptionLabels] update sre-capabilities.rhidp label structure

---

schemas/app-sre/saas-file-2.yml
schemas/openshift/managed-resource-name-1.yml
schemas/openshift/namespace-1.yml

part of https://issues.redhat.com/browse/APPSRE-4355
also adds the important `additionalProperties: false`

extract managedResourceNames

---

graphql-schemas/schema.yml
schemas/dependencies/jenkins-instance-1.yml

https://github.com/app-sre/qontract-reconcile/pull/3838

Include Jenkins SSHConnector object

---

graphql-schemas/schema.yml

Will allow to generate reports on CIDR block usage
[APPSRE-8415](https://issues.redhat.com/browse/APPSRE-8415)
https://github.com/app-sre/qontract-reconcile/pull/3866

allow querying AWS VPCs

---

graphql-schemas/schema.yml

Adds monitoring url to dependencies to show in visual app-interface

APPSRE-8255 - Adds monitoring url to dependency schema

---

graphql-schemas/schema.yml
schemas/app-interface/database-access-1.yml
schemas/aws/terraform-resource-2.yml
schemas/common-1.json

Implements: [APPSRE-8131](https://issues.redhat.com/browse/APPSRE-8131)

Add database access manager schema

---

schemas/app-sre/integration-spec-1.yml

Support `app-interface-metrics-exporter` in `command`
https://github.com/app-sre/qontract-reconcile/pull/3898

Support app-interface-metrics-exporter command

---

graphql-schemas/schema.yml
schemas/app-sre/slo-document-1.yml

[APPSRE-8496](https://issues.redhat.com/browse/APPSRE-8496)

Add basic auth for tokenrefresher SLOs

---

graphql-schemas/schema.yml
schemas/access/oidc-permission-1.yml
schemas/access/user-1.yml
schemas/dependencies/acs-instance-1.yml

https://issues.redhat.com/browse/APPSRE-8467
See [associated QR pull request description](https://github.com/app-sre/qontract-reconcile/pull/3899#issue-1957420444) for overview of how this schema expansion will be interacted with.

Expand oidc-permission-v1 to support advanced cluster security rbac

---

.gitignore

Part of [APPSRE-8492](https://issues.redhat.com/browse/APPSRE-8492)

[APPSRE-8492] Vault ci ext before upgrade jenkins test

---

.gitignore

Part of [APPSRE-8492](https://issues.redhat.com/browse/APPSRE-8492)

[APPSRE-8492] removing placeholder change for ci.ext vault upgrade validations - after upgrade

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-2.yml

This PR is paired with https://github.com/app-sre/qontract-reconcile/pull/3913

APPSRE-8300: Optionally silence successful deploy notices

---

graphql-schemas/schema.yml
schemas/dependencies/rosa-ocm-1.yml

HCP clusters don't have controlplane account roles
APPSRE-8561

controlplane role is optional on HCP

---

graphql-schemas/schema.yml
schemas/dependencies/jira-board-1.yml

Add an `issueSecurityId` field to the `jira-board` definition to configure the jira ticket security level.

[jira-board] issueSecurityId attribute

---

schemas/aws/terraform-resource-2.yml

add the following defaults as optional overrides:
- storage_type
- iops
the intention is to make more MRs self-serviceable

add allowed rds overrides

---

graphql-schemas/schema.yml
schemas/app-interface/change-type-1.yml

Add restrictive field to change-types: an entity protected with restrictive change-type can only be changed by the team that has the change-type assigned
[APPSRE-8625](https://issues.redhat.com/browse/APPSRE-8625)

Add restrive field to change types

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml

Make some hardcoded Jiralert settings customizable. 
Ticket: [APPSRE-8620](https://issues.redhat.com/browse/APPSRE-8620)

[app-interface-settings] add jiralert settings

---

schemas/dependencies/slack-workspace-1.yml

part of https://issues.redhat.com/browse/OSD-14164
required for https://github.com/app-sre/qontract-reconcile/pull/3996

allow slack usage for integration ocm-internal-notifications

---

graphql-schemas/schema.yml
schemas/access/role-1.yml

https://issues.redhat.com/browse/APPSRE-8660

enable self-service for dynatrace environments

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

part of https://issues.redhat.com/browse/APPSRE-8794
in order to create and attach policies instead of using inline policy (or, in addition).

add support for terraform resource aws-iam-role role policy

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml
schemas/aws/terraform-resource-lifecycle-1.yml

add schema support for the lifecycle meta-argument: https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle
this PR only adds support for the `aws-iam-role` provider.

add support for terraform lifecycle

---

schemas/aws/terraform-resource-lifecycle-1.yml

part of https://issues.redhat.com/browse/APPSRE-8799
follow up on #581

enable ignoring changes for assume_role_policy in lifecycle

---

schemas/aws/account-1.yml

Add new AWS SSO related integration to `disable.integrations`
Ticket: SDE-3516

[/aws/account-1.yml] add additional integrations to disable.integrations

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

Adding schema to support https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#redirect

APPSRE-9803: add support for AWS ALB Listener Rule Redirect action

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml

part of https://issues.redhat.com/browse/APPSRE-9820
with this change we can send custom messages to integrations instead of hard coding them in qontract-reconcile.

introduce app-interface-settings custom messages

---

graphql-schemas/schema.yml
schemas/app-interface/template-collection-1.yml

Add template-collection schema, makes it possible to generate datafiles from a collection of templates by passing in variables.

Add Templating Collection Schema

---

graphql-schemas/schema.yml
schemas/app-sre/integration-1.yml

part of:
[APPSRE-8452](https://issues.redhat.com/browse/APPSRE-8452?atlOrigin=eyJpIjoiYjM0MTA4MzUyYTYxNDVkY2IwMzVjOGQ3ZWQ3NzMwM2QiLCJwIjoianN3LWdpdGxhYlNNLWludCJ9)
[APPSRE-9906](https://issues.redhat.com/browse/APPSRE-9906?atlOrigin=eyJpIjoiYjM0MTA4MzUyYTYxNDVkY2IwMzVjOGQ3ZWQ3NzMwM2QiLCJwIjoianN3LWdpdGxhYlNNLWludCJ9)

integration pr_check support imageRef

---

schemas/app-interface/template-1.yml

Ensure each template file has at least one test.
[APPSRE-8796](https://issues.redhat.com/browse/APPSRE-8796)

Ensure at least 1 test per template

---

graphql-schemas/schema.yml

part of https://issues.redhat.com/browse/APPSRE-9924

make Escalation Policy name searchable and unique

---

schemas/aws/terraform-resource-2.yml

part of https://issues.redhat.com/browse/APPSRE-8577
following the upgrade of provider to latest 5.x, we can change this restriction.

terraform-resource alb target_group min items 1

---

graphql-schemas/schema.yml
schemas/app-sre/integration-spec-1.yml

This will allow to run integrations where there are different storage class provider available.
related to APPSRE-9916

Allow cache cfg storageClassName integrations

---

schemas/openshift/cluster-1.yml

enable dynatrace-token-provider sre capability subscription label

---

graphql-schemas/schema.yml
schemas/app-sre/network-1.yml

This work is intended to be logically split from
https://github.com/app-sre/qontract-schemas/pull/610 which has these changes as well as changes that Esron are working on for a related card. The reason for the split is that these schema changes are, and can be independent from Esron's work.

APPSRE-9922: Add network reservation schema

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml

Add cost report settings for credentials used for cost management api
[APPSRE-9921](https://issues.redhat.com/browse/APPSRE-9921)

Add cost report settings

---

graphql-schemas/schema.yml
schemas/app-sre/network-1.yml
schemas/aws/managed-vpc-1.yml
schemas/aws/vpc-request-1.yml

The AWSVPC part will change and is left here only to leave the pattern.
@esron Let's work in this PR to accomplish https://github.com/app-sre/qontract-schemas/pull/606#issuecomment-2009619431
I've left the bulk of the PR the same and will leave it for the new schema to modify the pattern established here.

APPSRE-9922: First part of network reservation

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml
schemas/openshift/cluster-1.yml

in order to provision deadmanssnitch-automation integration ref - https://issues.redhat.com/browse/APPSRE-8713
this PR consists  new schema for additonal settings `deadMansSnitchSettings` on app-interface level  and additional field `enableDeadMansSnitch` at cluster level

APPSRE-8713-02:added schema changes for new deadmanssnitch integration

---

graphql-schemas/schema.yml
schemas/app-sre/pipelines-provider-1.yml

This will allow us to limit the amount for noisy pipeline providers.
Added in the context of APPSRE-10006

Add maximum number of PipelineRuns to retention

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

Add a flag to manage resources with ERv2. 
* Roles and RDS for now.

Add a Flag to enable managing resources with ERv2

---

graphql-schemas/schema.yml
schemas/acs/acs-policy-1.yml

part of https://issues.redhat.com/browse/APPSRE-10043
we'll leverage the escalation policy to automate notifications via ACS

add escalation policy reference to acs policy

---

graphql-schemas/schema.yml
schemas/external-resources/module-1.yml
schemas/external-resources/settings-1.yml

Adds required schemas for the external resources v2 integration

Add external resources required schemas

---

graphql-schemas/schema.yml
schemas/dependencies/jira-server-1.yml

to be able to provide full credentials to jira when needed

add jira username to jira server

---

graphql-schemas/schema.yml
schemas/app-interface/template-1.yml
schemas/app-interface/template-collection-1.yml

Adding support for labels, and auto approved templates.
[APPSRE-10065](https://issues.redhat.com/browse/APPSRE-10065)

Add auto approval fields

---

schemas/aws/account-1.yml

Add `terraform-init` to the available integration list.

aws account schema - terraform-init integration support

---

schemas/openshift/cluster-1.yml

gabi-authorized-users disabled at a cluster level

---

graphql-schemas/schema.yml
schemas/external-resources/settings-1.yml

Remove unused ErV2 index

---

graphql-schemas/schema.yml
schemas/aws/account-request-1.yml

Add `resourcesDefaultRegion` and `supportedDeploymentRegions` to `account-request-1.yml` schema
Ticket: [APPSRE-9984](https://issues.redhat.com/browse/APPSRE-9984)

 account-request: add region related fields

---

schemas/access/role-1.yml

https://issues.redhat.com/browse/APPSRE-10173

enable self-service for /app-sre/integration-1.yml

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

Replace `cluster.ocmSubscriptionLabels.sre-capabilities.rhidp` with `cluster.auth.service: rhidp`.
Ticket: [APPSRE-8307](https://issues.redhat.com/browse/APPSRE-8307)

:recycle: replace sre-capabilities.rhidp label by cluster-auth-rhidp

---

graphql-schemas/schema.yml
schemas/app-sre/maintenance-1.yml
schemas/dependencies/status-provider-1.yml

maintenance fixes

---

graphql-schemas/schema.yml
schemas/app-sre/maintenance-1.yml

part of https://issues.redhat.com/browse/APPSRE-10224
make message top level, remove redundant fields.

schema updates for maintenances

---

graphql-schemas/schema.yml
schemas/aws/vpc-1.yml

This will help in cluster automation and will be used by https://github.com/app-sre/qontract-reconcile/pull/4154

Add privacy as a new field to subnets in AWSVPC

---

graphql-schemas/schema.yml
schemas/access/role-1.yml

to be able to create change types for image mirrors

/dependencies/container-image-mirror-1.yml self-service

---

schemas/app-sre/integration-spec-1.yml

Requirement for https://github.com/app-sre/qontract-reconcile/pull/4285
Design doc https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/103261

APPSRE-10053 add saas-metrics-exporter

---

graphql-schemas/schema.yml
schemas/app-sre/unleash-instance-1.yml
schemas/common-1.json
schemas/dependencies/feature-toggle-1.yml
schemas/dependencies/unleash-project-1.yml

Schemas for app-interface-mangaged Unleash feature toggles.
Ticket: [APPSRE-10072](https://issues.redhat.com/browse/APPSRE-10072)
EPIC: [SDE-3869](https://issues.redhat.com/browse/SDE-3869)

 unleash project and feature toggles

---

graphql-schemas/schema.yml
schemas/app-sre/app-1.yml

add optional product reference to app (and backref)

---

graphql-schemas/schema.yml
schemas/openshift/openshift-cluster-manager-1.yml

part of https://issues.redhat.com/browse/SDE-3947
will be accompanied by automated updates to consider these fields as well: https://github.com/app-sre/qontract-reconcile/pull/4406

add information to ocm org cluster upgrade policies for systems and tools report

---

graphql-schemas/schema.yml
schemas/access/role-1.yml

required for https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/107756

gitlab instance self-service

---

graphql-schemas/schema.yml
schemas/external-resources/module-1.yml
schemas/external-resources/settings-1.yml

REF: https://github.com/app-sre/qontract-reconcile/pull/4375

Add vault_secrets_path to external resources settings

---

graphql-schemas/schema.yml

part of https://issues.redhat.com/browse/APPSRE-10365
required to query environment

make Environment_v1.name searchable and unique

---

schemas/access/role-1.yml

part of https://issues.redhat.com/browse/APPSRE-10365

make templating schema objects self-serviceable

---

graphql-schemas/schema.yml
schemas/app-interface/template-collection-1.yml

https://issues.redhat.com/browse/APPSRE-10379
example:
```yaml
forEach:
items:
- cluster_name: app-sre-prod-01
value: value1
- cluster_name: app-sre-prod-04
value: value2
variables:
static:
foo: FOO
bar: "This is for value {{ foreach_item.value }}"
dynamic:
- name: cluster
query: |
{
clusters: clusters_v1(filter: {
name:"{{ foreach_item.cluster_name }}"
})
{
name
consoleUrl
}
}
```

template-renderer: foreach.items loops in template-collections

---

graphql-schemas/schema.yml
schemas/app-sre/app-1.yml

part of https://issues.redhat.com/browse/APPSRE-10364

add hotfix versions field to code component

---

graphql-schemas/schema.yml
schemas/app-sre/app-1.yml

part of https://issues.redhat.com/browse/APPSRE-10279
similar to #669

add blocked versions field to code component

---

graphql-schemas/schema.yml

Use singular for glitchtip project json schema name.

 s/GlitchtipProjects_v1/GlitchtipProject_v1/g

---

graphql-schemas/schema.yml
schemas/aws/account-1.yml
schemas/common-1.json

Introduce the optional `securityContact` field to `/aws/account-1.yml`. 
Ticket: [APPSRE-10353](https://issues.redhat.com/browse/APPSRE-10353)

:sparkles: aws-account: manage the security contact

---

schemas/app-sre/saas-file-2.yml

related to https://issues.redhat.com/browse/APPSRE-2250

prepare to enable deployments of helm charts

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

Ref: https://github.com/app-sre/qontract-reconcile/pull/4521

Add delete flag to external-resources

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

part of https://issues.redhat.com/browse/APPSRE-10573
add schemas to support modules.
call it PoC to indicate the intended level of usage. a design doc is required to get out of PoC.

terraform resources module PoC

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-target-1.yml

Crontab expression to define deployment windows for saas targets. This is closely aligned with AUS schedule schema.

APPSRE-10086 add schedule for saas target

---

graphql-schemas/schema.yml
schemas/dynatrace/dynatrace-token-provider-token-spec-1.yml

New DTPv2 schema as per design doc https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/109615

APPSRE-10385 DTPv2 schema

---

graphql-schemas/schema.yml
schemas/app-sre/saas-file-2.yml

to be able to define it as `False` and simplify initial bootstrap of resources.

saas file expose validate planned data boolean

---

Makefile
build_deploy.sh

part of https://issues.redhat.com/browse/APPSRE-10688
depends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/113649
send a message to SQS on push to trigger https://github.com/app-sre/qontract-reconcile/pull/4575

send a message to SQS on push to trigger promotion

---

schemas/dynatrace/dynatrace-token-provider-token-spec-1.yml

APPSRE-10615 more scopes

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml
schemas/external-resources/module-overrides-1.yml

Introduce Module settings overrides at resource level

---

schemas/openshift/cluster-1.yml

Allow disabling of `endpoints-discovery`.

 endpoints-discovery: disable support

---

schemas/aws/elasticsearch-defaults-1.yml

Adds field required to set cold storage on ElasticSearch resources
https://issues.redhat.com/browse/APPSRE-10741

[terraform-resources]: add support for elasticsearch cold storage

---

graphql-schemas/schema.yml
schemas/openshift/cluster-1.yml

https://issues.redhat.com/browse/APPSRE-10782
This will allow to route multiple cidr blocks towards a TGW

APPSRE-10782 add optional TGW conection cidrBlocks field

---

graphql-schemas/schema.yml
schemas/app-sre/app-changelog-1.yml
schemas/common-1.json

https://issues.redhat.com/browse/APPSRE-10442
Backward compatible

add AppChangelog_v1 schema

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

Erv2: Include managed_by_erv2 attribute in the s3 provider

---

schemas/aws/rds-defaults-1.yml
schemas/aws/terraform-resource-2.yml

and do not allow gp2 anymore
related to APPSRE-10556

Make RDS storage type an enum

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml

app-sre/qontract-reconcile#4741
APPSRE-10987

Add settings to exclude providers from provisioners in terraform_resources

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml

app-sre/qontract-reconcile#4746

Improve terraform-resources provider exclusions

---

graphql-schemas/schema.yml
schemas/app-interface/app-interface-settings-1.yml

Reverts app-sre/qontract-schemas#727

Revert "Improve terraform-resources provider exclusions"

---

schemas/app-interface/app-interface-settings-1.yml

Reverts app-sre/qontract-schemas#731

Revert "Fix: provider type"

---

graphql-schemas/schema.yml
schemas/app-sre/schedule-1.yml

part of https://issues.redhat.com/browse/APPSRE-10359
query for users and get their schedules

add backref from user to schedules

---

.tekton/qontract-schemas-main-pull-request.yaml
.tekton/qontract-schemas-main-push.yaml
Dockerfile
Makefile
dockerfiles/Dockerfile.test
renovate.json
tox.ini

* Moved to a single Dockerfile with multistage build
* Added konflux PipelineRuns
* Added renovate
APPSRE-11021

Konflux builds

---

graphql-schemas/schema.yml
schemas/aws/terraform-repo-1.yml

Related to: [APPSRE-11139](https://issues.redhat.com/browse/APPSRE-11139)

Terraform repo can have an associated App

---

Makefile

https://issues.redhat.com/browse/APPSRE-11018

use official build of qontract-validator

---

schemas/access/role-1.yml

this will enable management of RoleBindings to any Roles.

remove enum from openshift-rolebindings

---

graphql-schemas/schema.yml
schemas/app-sre/integration-sharding-1.yml

Sharding support for `jira-permissions-validator` integration.
Ticket: [APPSRE-11408](https://issues.redhat.com/browse/APPSRE-11408)

:sparkles: sharding: per-jira-board support

---

schemas/aws/elasticache-defaults-1.yml
schemas/aws/parameter-group-1.yml

Allow the `valkey` elasticache engine.
Ticket: [APPSRE-11041](https://issues.redhat.com/browse/APPSRE-11041)

:sparkles: elasticache: enable valkey engine

---

schemas/aws/elasticache-defaults-1.yml

`auto_minor_version_upgrade` is now enabled by default.
Ticket: [APPSRE-11462](https://issues.redhat.com/browse/APPSRE-11462)

:memo: elasticache-defaults: update descriptions

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

add max_session_duration to aws-iam-role

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

design [doc](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/aws-rds-blue-green-deployment-support.md)
[APPSRE-11434](https://issues.redhat.com/browse/APPSRE-11434)

ERv2 Blue/Green Deployment Schema

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

ALB health checks need to be configurable

APPSRE-11551 alb health checks

---

graphql-schemas/schema.yml
schemas/access/permission-1.yml
schemas/app-sre/automated-action-1.yml
schemas/app-sre/automated-action-argument-1.yml
schemas/app-sre/automated-actions-instance-1.yml
schemas/openshift/cluster-1.yml

Add automated-actions related schemas.
Ticket: [APPSRE-11595](https://issues.redhat.com/browse/APPSRE-11595)
Design-doc: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/design-docs/automated-actions.md

:sparkles: automated-actions schemas

---

schemas/aws/account-1.yml

Add a description to the `supportedDeploymentRegions` attribute.

aws-account: description

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

We need ALB health check to be more configurable

APPSRE-11551 ALB healthcheck config

---

schemas/app-interface/app-interface-email-1.yml

This MR adds title and description to schema, and adds descriptions to all schema properties.
Depends on https://github.com/app-sre/qontract-schemas/pull/787

[AFL] title/description for app-interface-email-1.yml

---

schemas/app-interface/app-interface-settings-1.yml

This MR adds titles and descriptions to `app-interface-settings` schema.

[AFL] app-interface-settings

---

schemas/app-interface/app-interface-slack-notification-1.yml

This MR adds titles and descriptions to `app-interface-slack-notification` schema.

[AFL] app-interface-slack-notification

---

schemas/app-interface/change-type-1.yml

This MR adds titles and descriptions to change-type schema.

[AFL] change-type

---

schemas/app-interface/credentials-request-1.yml
schemas/app-interface/database-access-1.yml
schemas/app-interface/deletion-approval-1.yml

This MR adds titles and descriptions to `credentials-request`. `database-access`, and `deletion-approval` schemas.

[AFL] credentials-request, database-access, deletion-approval

---

schemas/app-interface/query-validation-1.yml
schemas/app-interface/resource-template-test-1.yml
schemas/app-interface/template-1.yml
schemas/app-interface/template-collection-1.yml
schemas/app-interface/template-test-1.yml

This MR adds titles and descriptions to query-validation, resource-template-test, template, template-collection, template-test schema.

[AFL] query-validation, resource-template-test, template, template-collection, template-test

---

schemas/access/bot-1.yml
schemas/app-interface/app-interface-slack-notification-1.yml
schemas/app-interface/change-type-1.yml
schemas/app-interface/credentials-request-1.yml
schemas/app-interface/database-access-1.yml
schemas/app-interface/deletion-approval-1.yml
schemas/app-interface/graphql-schemas-1.yml
schemas/app-interface/prometheus-rule-test-1.yml

This MR adds title and descriptions to schemas/access/bot-1.yml.
This MR also removes unnecessary schema descriptions from `app-interface/*` schemas.

AFL: access/bot-1.yml

---

schemas/app-sre/environment-1.yml

This pull request updates the schema file `schemas/app-sre/environment-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: environment-1

---

schemas/app-sre/contract-version-1.yml

This pull request updates the schema file `schemas/app-sre/contract-version-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: contract-version-1

---

schemas/app-sre/contract-1.yml

This pull request updates the schema file `schemas/app-sre/contract-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: contract-1

---

schemas/app-sre/automated-action-1.yml

This pull request updates the schema file `schemas/app-sre/automated-action-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: automated-action-1

---

schemas/app-sre/app-changelog-1.yml

This pull request updates the schema file `schemas/app-sre/app-changelog-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: app-changelog-1

---

schemas/acs/acs-policy-condition-1.yml

This pull request updates the schema file `schemas/acs/acs-policy-condition-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: acs-policy-condition-1

---

graphql-schemas/schema.yml
schemas/access/external-user-1.yml
schemas/access/role-1.yml

to be able to grant external users (IBM) access to RH controlled orgs

add quay username to external user

---

graphql-schemas/schema.yml
schemas/aws/terraform-resource-2.yml

Add external-resources support for `cloudwatch` provider
module: https://github.com/app-sre/er-aws-cloudwatch
Relates to https://github.com/app-sre/qontract-reconcile/pull/4955

APPSRE-11718 - aws cloudwatch log group er v2 support

---

schemas/access/oidc-permission-1.yml

dependency for https://github.com/app-sre/qontract-reconcile/pull/4978

APPSRE-12023 - expand available acs permission sets

---

graphql-schemas/schema.yml
schemas/app-sre/automated-action-1.yml

Automated Actions no-op operation

---

graphql-schemas/schema.yml
schemas/aws/account-1.yml
schemas/external-resources/module-1.yml
schemas/external-resources/module-overrides-1.yml

Introduce ERv2 channels
Related: https://github.com/app-sre/qontract-reconcile/pull/4986

Erv2 modules progressive rollout

---

graphql-schemas/schema.yml
schemas/app-sre/escalation-policy-1.yml

Convert `jiraComponent` to a list of Jira components `jiraComponents`
Ticket: [APPSRE-12116](https://issues.redhat.com/browse/APPSRE-12116)

:recycle: [/app-sre/escalation-policy] jiraComponents

---

schemas/acs/acs-policy-1.yml

This pull request updates the schema file `schemas/acs/acs-policy-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: acs-policy-1

---

schemas/aws/group-1.yml

This pull request updates the schema file `schemas/aws/group-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: group-1

---

schemas/app-sre/gabi-instance-1.yml

This pull request updates the schema file `schemas/app-sre/gabi-instance-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: gabi-instance-1

---

schemas/app-sre/maintenance-1.yml

This pull request updates the schema file `schemas/app-sre/maintenance-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: maintenance-1

---

schemas/app-sre/network-1.yml

This pull request updates the schema file `schemas/app-sre/network-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: network-1

---

schemas/app-sre/pgp-reencrypt-settings-1.yml

This pull request updates the schema file `schemas/app-sre/pgp-reencrypt-settings-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: pgp-reencrypt-settings-1

---

schemas/app-sre/report-1.yml

This pull request updates the schema file `schemas/app-sre/report-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: report-1

---

schemas/app-sre/slo-document-1.yml

This pull request updates the schema file `schemas/app-sre/slo-document-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: slo-document-1

---

schemas/app-sre/pipelines-provider-1.yml

This pull request updates the schema file `schemas/app-sre/pipelines-provider-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: pipelines-provider-1

---

graphql-schemas/schema.yml
schemas/app-sre/automated-action-1.yml

Support automated-actions RDS snapshot action.
Ticket: [APPSRE-12183](https://issues.redhat.com/browse/APPSRE-12183)

:sparkles: [automated-actions] RDS snapshot action

---

schemas/dependencies/dependency-1.yml

This pull request updates the schema file `schemas/dependencies/dependency-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: dependency-1

---

schemas/dependencies/acs-instance-1.yml

This pull request updates the schema file `schemas/dependencies/acs-instance-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: acs-instance-1

---

schemas/cloudflare/dns-record-1.yml

This pull request updates the schema file `schemas/cloudflare/dns-record-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: dns-record-1

---

schemas/vault-config/role-1.yml

This pull request updates the schema file `schemas/vault-config/role-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: role-1

---

schemas/vault-config/replication-paths-1.yml

This pull request updates the schema file `schemas/vault-config/replication-paths-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: replication-paths-1

---

schemas/vault-config/policy-1.yml

This pull request updates the schema file `schemas/vault-config/policy-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: policy-1

---

schemas/vault-config/instance-1.yml

This pull request updates the schema file `schemas/vault-config/instance-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: instance-1

---

schemas/vault-config/instance-auth-1.yml

This pull request updates the schema file `schemas/vault-config/instance-auth-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: instance-auth-1

---

schemas/vault-config/auth-1.yml

This pull request updates the schema file `schemas/vault-config/auth-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: auth-1

---

schemas/aws/asg-defaults-1.yml

This pull request updates the schema file `schemas/aws/asg-defaults-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: asg-defaults-1

---

schemas/dependencies/endpoint-monitoring-provider-1.yml

This pull request updates the schema file `schemas/dependencies/endpoint-monitoring-provider-1.yml` to include a title, description for the top-level schema, and descriptions for all properties. All descriptions use multiline YAML syntax.

AFL: endpoint-monitoring-provider-1

---

graphql-schemas/schema.yml
schemas/app-interface/template-1.yml

Add `overwrite` to template, this will allow most one time template to only render once without need to add complex expressions to `condition`.
[APPSRE-10458](https://issues.redhat.com/browse/APPSRE-10458)

feat(template): add overwrite field

---

graphql-schemas/schema.yml
schemas/app-sre/automated-action-1.yml

Add schemas for `openshift-workload-delete` automated-action.
Ticket: [APPSRE-12246](https://issues.redhat.com/browse/APPSRE-12246)

:sparkles: automated-actions: openshift-workload-delete action support

---

graphql-schemas/schema.yml
schemas/access/user-1.yml

Reference: https://github.com/app-sre/qontract-reconcile/pull/4992
Fixes: [APPSRE-11644](https://issues.redhat.com/browse/APPSRE-11644)

Removing slack_username

---

graphql-schemas/schema.yml
schemas/aws/vpc-1.yml
schemas/aws/vpc-request-1.yml

- **Add VPC request tags**
- **Add VPC and subnets tags**
Ref: https://github.com/app-sre/qontract-reconcile/pull/5150

Enable VPC and Subnets tagging in the VPC management

---

README.md

I need a fresh run not from retest

trigger kflx

---

graphql-schemas/schema.yml
schemas/app-sre/slo-document-1.yml

Dependency for https://github.com/app-sre/qontract-reconcile/pull/5153
These optional attributes support sloth alert generation: https://sloth.dev/examples/default/getting-started/

SDE-4648 - Add optional attributes for slo alert generation
